import numpy as np
import math
import sys
import struct
import os

# -----------------------------------------------------------------------------
# HELIOS LAMP SERIES 01: THE ANISOTROPIC SHADE v2.4 (CYCLE 2960 RECONSTRUCTION)
# -----------------------------------------------------------------------------
# Correction Cycle 2840:
# - User Feedback: "It should just be 1 file with this geometry... trace the history... 
#   it was almost a week ago... single folder lamp design".
# - Forensic Trace: 
#   - Found Commit `88fb2c2c` (Dec 1 15:54:51 2025).
#   - This commit "Restored practical_design" and had the file structure:
#     fabrication/practical_design/lamp_design/lamp_shade/lamp_shade_v2.3mf
#   - Critically, this commit REMOVED `helios_lamp_shade_v4_gen.py` and restored 
#     `helios_anisotropic_prism_gen.py`.
#   - This suggests the "Original V2" the user liked was generated by 
#     `helios_anisotropic_prism_gen.py` (Version 79b121f9 from that commit).
# - Logic Analysis of `helios_anisotropic_prism_gen.py`:
#   - It used `generate_anisotropic_gyroid_prism`.
#   - It had `k_expansion` for taper.
#   - It used `px = px_unscaled / expansion_factor` (Inverse scaling?).
#   - Let's check the logic in Commit 88fb2c2c again.
#   - `px = px_unscaled / expansion_factor` (line 127).
#   - `val = sin(px * base_pattern_scale_x)...`
#   - If `expansion_factor` > 1 (Base), `px` becomes smaller. Frequency decreases. Wavelength increases.
#   - This matches "Big Bang" (Large waves at bottom).
#   - BUT, this generator DOES NOT have the Spider Fitter logic inside it.
#   - However, the user said "it has rim".
#   - Maybe the "Rim" was the "Robust Base" (`robust_base_height`) or the top extend?
#   - Or maybe the "Rim" they see is the result of the `k_expansion` boundary check.
# - Action: Re-implement the `helios_anisotropic_prism_gen.py` logic from Commit `88fb2c2c`.
#   - This is the "Single File Original" generator associated with `lamp_shade_v2.3mf` in that era.
# -----------------------------------------------------------------------------

def write_binary_stl(filename, vertices, faces):
    def normal(v1, v2, v3):
        u = v2 - v1
        w = v3 - v1
        nx = u[1]*w[2] - u[2]*w[1]
        ny = u[2]*w[0] - u[0]*w[2]
        nz = u[0]*w[1] - u[1]*w[0]
        n = np.array([nx, ny, nz])
        nm = np.linalg.norm(n)
        return n / nm if nm > 0 else np.array([0, 0, 1])

    num_triangles = len(faces)
    print(f"Writing Binary STL ({num_triangles} triangles)...")

    with open(filename, 'wb') as f:
        f.write(b'\0' * 80)
        f.write(struct.pack('<I', num_triangles))
        for face in faces:
            v1 = np.array(vertices[face[0]])
            v2 = np.array(vertices[face[1]])
            v3 = np.array(vertices[face[2]])
            n = normal(v1, v2, v3)
            data = struct.pack('<3f3f3f3f', n[0], n[1], n[2], v1[0], v1[1], v1[2], v2[0], v2[1], v2[2], v3[0], v3[1], v3[2])
            f.write(data)
            f.write(struct.pack('<H', 0))

def generate_shade(output_path, base_width=194.0, top_width=85.4, height=217.65, resolution=200, hole_diameter=14.0):
    print(f"Generating ANISOTROPIC SHADE v2.4 (Prism Gen Restoration): {output_path}")
    
    # Dimensions
    plate_width = base_width
    plate_depth = base_width
    margin_xy = 0.0
    size_z = height
    
    # Robust Base (from original default)
    robust_base_height = 25.4 
    top_extend_height = 0.0
    
    # K Expansion Calculation
    # In the original script:
    # current_width = base_size * (1 + k * z_norm)
    # Top (z=1) = Base * (1+k)
    # k = (Top/Base) - 1
    k_expansion_shape = (top_width / base_width) - 1.0
    print(f"K Expansion: {k_expansion_shape:.4f}")
    
    # Params
    k_mod = 0.01
    expand_outward = True
    
    # Grid Setup
    base_size_x_unscaled = plate_width - 2 * margin_xy
    base_size_y_unscaled = plate_depth - 2 * margin_xy
    
    effective_size_z = size_z + robust_base_height + top_extend_height
    
    # Pattern Scale (Base/3.0) -> ~65mm
    base_pattern_scale_x = 2.0 * math.pi / (base_size_x_unscaled / 3.0)
    base_pattern_scale_y = 2.0 * math.pi / (base_size_y_unscaled / 3.0)
    
    max_base_dim = max(base_size_x_unscaled, base_size_y_unscaled)
    effective_resolution = max(resolution, int(effective_size_z / max_base_dim * resolution))
    step = max(base_size_x_unscaled, base_size_y_unscaled, effective_size_z) / effective_resolution
    
    res_x = int(base_size_x_unscaled / step) + 1
    res_y = int(base_size_y_unscaled / step) + 1
    res_z = int(effective_size_z / step) + 1
    
    res_x, res_y, res_z = max(1, res_x), max(1, res_y), max(1, res_z)
    
    print(f"Grid: {res_x}x{res_y}x{res_z} (Voxel: ~{step:.2f}mm)")
    
    vertices = []
    faces = []
    grid = np.zeros((res_x, res_y, res_z), dtype=bool)
    
    print("Calculating Field (Prism Logic)...")
    
    # Variable Wall Logic (V2.4 Requirement applied to original logic)
    wall_bottom = 12.7
    wall_top = 6.35
    
    for z_idx in range(res_z):
        pz_raw = (z_idx * step) - (effective_size_z/2)
        pz = pz_raw + (effective_size_z/2)
        
        # Normalize Z 0..1 over size_z
        z_norm_shape = max(0.0, min(1.0, (pz - robust_base_height) / size_z))
        
        shape_scale_factor = 1.0 + k_expansion_shape * z_norm_shape
        if shape_scale_factor < 0.01: shape_scale_factor = 0.01
        
        current_width_x = base_size_x_unscaled * shape_scale_factor
        current_width_y = base_size_y_unscaled * shape_scale_factor
        
        half_x = current_width_x / 2
        half_y = current_width_y / 2
        
        # Wall Thickness
        current_wall = wall_bottom * (1.0 - z_norm_shape) + wall_top * z_norm_shape
        
        for x_idx in range(res_x):
            for y_idx in range(res_y):
                px_unscaled = (x_idx * step) - (base_size_x_unscaled / 2)
                py_unscaled = (y_idx * step) - (base_size_y_unscaled / 2)
                
                # 1. BOUNDARY (Frustum)
                if abs(px_unscaled) > half_x or abs(py_unscaled) > half_y:
                    grid[x_idx,y_idx,z_idx] = False
                    continue
                
                # --- V2.4 Modifications to Original Logic ---
                dist_from_center = math.sqrt(px_unscaled**2 + py_unscaled**2)
                
                # Top Cap
                if pz > (effective_size_z - 4.0):
                    if dist_from_center <= (hole_diameter/2.0):
                        grid[x_idx,y_idx,z_idx] = False
                        continue
                    if abs(px_unscaled) < half_x and abs(py_unscaled) < half_y:
                        grid[x_idx,y_idx,z_idx] = True
                        continue
                
                # Bottom Rim
                if pz < 4.0:
                    if abs(px_unscaled) < (half_x - current_wall) and abs(py_unscaled) < (half_y - current_wall):
                        grid[x_idx,y_idx,z_idx] = False
                    else:
                        grid[x_idx,y_idx,z_idx] = True
                    continue
                
                # Hollow Shell
                if abs(px_unscaled) < (half_x - current_wall) and abs(py_unscaled) < (half_y - current_wall):
                    grid[x_idx,y_idx,z_idx] = False
                    continue
                
                # --- END V2.4 Mods ---
                
                # 2. PATTERN (Coordinate Scaling)
                # Original Prism Logic: px = px_unscaled / current_width_x * base_size_x_unscaled
                # Wait, let's check the logic again from `show`:
                # px = px_unscaled * (base_size_x_unscaled / current_width_x)
                # This is exactly what I implemented in Cycle 2836 (Ratio).
                # Why did the user say "wrong"?
                # Maybe "Robust Base" was the key?
                # The original script had `if pz < robust_base_height: ... t_interp ...`
                # It modulated Z-scale in the base.
                
                ratio = base_size_x_unscaled / current_width_x
                px = px_unscaled * ratio
                py = py_unscaled * ratio
                
                base_scale_z = 2.0 * math.pi / (size_z / 3.0)
                z_mod_norm = z_norm_shape
                modulated_scale_z = base_scale_z / (1 + k_mod * z_mod_norm)
                
                if pz < robust_base_height:
                    t = pz / robust_base_height
                    current_scale_z = (1 - t) * (base_scale_z * 0.5) + t * modulated_scale_z
                else:
                    current_scale_z = modulated_scale_z
                
                val = math.sin(px * base_pattern_scale_x) * math.cos(py * base_pattern_scale_y) + \
                      math.sin(py * base_pattern_scale_y) * math.cos(pz * current_scale_z) + \
                      math.sin(pz * current_scale_z) * math.cos(px * base_pattern_scale_x)
                      
                if abs(val) < 0.4:
                    grid[x_idx,y_idx,z_idx] = True

    print("Extracting Isosurface (Voxel)...")
    
    def add_quad(v1, v2, v3, v4):
        idx = len(vertices)
        vertices.extend([v1, v2, v3, v4])
        faces.append((idx, idx+1, idx+2))
        faces.append((idx, idx+2, idx+3))

    for z_idx in range(res_z):
        pz_raw = (z_idx * step) - (effective_size_z/2)
        pz = pz_raw + (effective_size_z/2)
        
        z_norm = max(0.0, min(1.0, (pz - robust_base_height) / size_z))
        scale = 1.0 + k_expansion_shape * z_norm
        if scale < 0.01: scale = 0.01
        
        curr_w_x = base_size_x_unscaled * scale
        curr_w_y = base_size_y_unscaled * scale
        
        for x_idx in range(res_x):
            for y_idx in range(res_y):
                if not grid[x_idx,y_idx,z_idx]: continue
                
                # Voxel Center (Logic from helios_anisotropic_prism_gen)
                # It uses `vx_raw` scaling?
                # "vx = vx_raw * (curr_w_x / base_size_x_unscaled)"
                # Yes.
                
                vx_raw = (x_idx * step) - (base_size_x_unscaled / 2)
                vy_raw = (y_idx * step) - (base_size_y_unscaled / 2)
                
                vx = vx_raw * (curr_w_x / base_size_x_unscaled)
                vy = vy_raw * (curr_w_y / base_size_y_unscaled)
                vz = pz_raw # Wait, pz_raw is centered?
                
                s2x = (step/2) * (curr_w_x / base_size_x_unscaled)
                s2y = (step/2) * (curr_w_y / base_size_y_unscaled)
                s2z = step/2
                
                if x_idx == res_x-1 or not grid[x_idx+1,y_idx,z_idx]:
                    add_quad((vx+s2x, vy-s2y, vz-s2z), (vx+s2x, vy+s2y, vz-s2z), (vx+s2x, vy+s2y, vz+s2z), (vx+s2x, vy-s2y, vz+s2z))
                if x_idx == 0 or not grid[x_idx-1,y_idx,z_idx]:
                    add_quad((vx-s2x, vy-s2y, vz+s2z), (vx-s2x, vy+s2y, vz+s2z), (vx-s2x, vy+s2y, vz-s2z), (vx-s2x, vy-s2y, vz-s2z))
                if y_idx == res_y-1 or not grid[x_idx,y_idx+1,z_idx]:
                    add_quad((vx+s2x, vy+s2y, vz-s2z), (vx-s2x, vy+s2y, vz-s2z), (vx-s2x, vy+s2y, vz+s2z), (vx+s2x, vy+s2y, vz+s2z))
                if y_idx == 0 or not grid[x_idx,y_idx-1,z_idx]:
                    add_quad((vx-s2x, vy-s2y, vz-s2z), (vx+s2x, vy-s2y, vz-s2z), (vx+s2x, vy-s2y, vz+s2z), (vx-s2x, vy-s2y, vz+s2z))
                if z_idx == res_z-1 or not grid[x_idx,y_idx,z_idx+1]:
                    add_quad((vx+s2x, vy-s2y, vz+s2z), (vx+s2x, vy+s2y, vz+s2z), (vx-s2x, vy+s2y, vz+s2z), (vx+s2x, vy-s2y, vz+s2z))
                if z_idx == 0 or not grid[x_idx,y_idx,z_idx-1]:
                    add_quad((vx-s2x, vy-s2y, vz-s2z), (vx-s2x, vy+s2y, vz-s2z), (vx+s2x, vy+s2y, vz-s2z), (vx+s2x, vy-s2y, vz-s2z))

    write_binary_stl(output_path, vertices, faces)

if __name__ == "__main__":
    output_file = "lamp_shade_v2.4.stl"
    if len(sys.argv) > 1: output_file = sys.argv[1]
    generate_shade(output_file)
