// jtag_system.v

// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module jtag_system (
		input  wire        clk_clk,                              //                           clk.clk
		output wire [31:0] injection_external_connection_export, // injection_external_connection.export
		input  wire        reset_reset_n                         //                         reset.reset_n
	);

	wire  [31:0] master_0_master_readdata;                      // mm_interconnect_0:master_0_master_readdata -> master_0:master_readdata
	wire         master_0_master_waitrequest;                   // mm_interconnect_0:master_0_master_waitrequest -> master_0:master_waitrequest
	wire  [31:0] master_0_master_address;                       // master_0:master_address -> mm_interconnect_0:master_0_master_address
	wire         master_0_master_read;                          // master_0:master_read -> mm_interconnect_0:master_0_master_read
	wire   [3:0] master_0_master_byteenable;                    // master_0:master_byteenable -> mm_interconnect_0:master_0_master_byteenable
	wire         master_0_master_readdatavalid;                 // mm_interconnect_0:master_0_master_readdatavalid -> master_0:master_readdatavalid
	wire         master_0_master_write;                         // master_0:master_write -> mm_interconnect_0:master_0_master_write
	wire  [31:0] master_0_master_writedata;                     // master_0:master_writedata -> mm_interconnect_0:master_0_master_writedata
	wire         mm_interconnect_0_pio_injection_s1_chipselect; // mm_interconnect_0:pio_injection_s1_chipselect -> pio_injection:chipselect
	wire  [31:0] mm_interconnect_0_pio_injection_s1_readdata;   // pio_injection:readdata -> mm_interconnect_0:pio_injection_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_injection_s1_address;    // mm_interconnect_0:pio_injection_s1_address -> pio_injection:address
	wire         mm_interconnect_0_pio_injection_s1_write;      // mm_interconnect_0:pio_injection_s1_write -> pio_injection:write_n
	wire  [31:0] mm_interconnect_0_pio_injection_s1_writedata;  // mm_interconnect_0:pio_injection_s1_writedata -> pio_injection:writedata

	jtag_system_master_0 #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) master_0 (
		.clk_clk              (clk_clk),                       //          clk.clk
		.clk_reset_reset      (~reset_reset_n),                //    clk_reset.reset
		.master_address       (master_0_master_address),       //       master.address
		.master_readdata      (master_0_master_readdata),      //             .readdata
		.master_read          (master_0_master_read),          //             .read
		.master_write         (master_0_master_write),         //             .write
		.master_writedata     (master_0_master_writedata),     //             .writedata
		.master_waitrequest   (master_0_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (master_0_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (master_0_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                               // master_reset.reset
	);

	jtag_system_pio_injection pio_injection (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (reset_reset_n),                                 //               reset.reset_n
		.address    (mm_interconnect_0_pio_injection_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_injection_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_injection_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_injection_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_injection_s1_readdata),   //                    .readdata
		.out_port   (injection_external_connection_export)           // external_connection.export
	);

	jtag_system_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                   (clk_clk),                                       //                                 clk_0_clk.clk
		.master_0_clk_reset_reset_bridge_in_reset_reset  (~reset_reset_n),                                //  master_0_clk_reset_reset_bridge_in_reset.reset
		.pio_injection_reset_reset_bridge_in_reset_reset (~reset_reset_n),                                // pio_injection_reset_reset_bridge_in_reset.reset
		.master_0_master_address                         (master_0_master_address),                       //                           master_0_master.address
		.master_0_master_waitrequest                     (master_0_master_waitrequest),                   //                                          .waitrequest
		.master_0_master_byteenable                      (master_0_master_byteenable),                    //                                          .byteenable
		.master_0_master_read                            (master_0_master_read),                          //                                          .read
		.master_0_master_readdata                        (master_0_master_readdata),                      //                                          .readdata
		.master_0_master_readdatavalid                   (master_0_master_readdatavalid),                 //                                          .readdatavalid
		.master_0_master_write                           (master_0_master_write),                         //                                          .write
		.master_0_master_writedata                       (master_0_master_writedata),                     //                                          .writedata
		.pio_injection_s1_address                        (mm_interconnect_0_pio_injection_s1_address),    //                          pio_injection_s1.address
		.pio_injection_s1_write                          (mm_interconnect_0_pio_injection_s1_write),      //                                          .write
		.pio_injection_s1_readdata                       (mm_interconnect_0_pio_injection_s1_readdata),   //                                          .readdata
		.pio_injection_s1_writedata                      (mm_interconnect_0_pio_injection_s1_writedata),  //                                          .writedata
		.pio_injection_s1_chipselect                     (mm_interconnect_0_pio_injection_s1_chipselect)  //                                          .chipselect
	);

endmodule
