import dolfinx.mesh
from mpi4py import MPI
import meshio
import numpy as np
import os
import sys
import subprocess
import shutil # Added shutil import

# --- CONFIGURATION ---
STL_PATH = "/app/fabrication/library/TPMS_Anisotropic_Prism_Artifact03/TPMS_Anisotropic_Prism_Optimized.stl"
GMSH_GEO_PATH = "/tmp/gyroid_mesh.geo" # Temporary GMSH .geo file
MESH_OUT_PATH = "/app/fabrication/analysis/optimized_prism_mesh.msh"

def generate_mesh_from_stl(stl_path, mesh_out_path, cell_size=5.0):
    """
    Generates a 3D mesh from an STL file using GMSH executable via subprocess.
    """
    print(f"Generating mesh from {stl_path} using GMSH executable...")

    # Create a basic GMSH .geo script to load the STL and mesh it
    geo_content = f"""
    SetFactory("OpenCASCADE");
    Merge "{stl_path}";
    // Get all 3D entities
    // Physical Volume(1) = {1};
    // Physical Surface(1) = { {Surface1}, {Surface2}, ...};
    // We need to identify the volume entity to mesh it.
    // GMSH often assigns tag 1 to the first imported volume.
    
    // Create a bounding box for the gyroid from the STL
    // Get the bounding box from trimesh to set Gmsh's meshing region
    // Placeholder - for now, just mesh the whole thing
    
    // Set mesh size
    Mesh.CharacteristicLengthMax = {cell_size};
    Mesh.CharacteristicLengthMin = {cell_size / 5.0};
    
    // Generate 3D mesh
    Mesh.MeshAlgorithm = 6; // DelQuad
    Mesh.Algorithm3D = 4; // Delaunay
    
    Volume v() = {1}; // Assuming tag 1 for the imported volume
    
    // Physical volume for FEniCSx
    Physical Volume("gyroid_volume") = {{v()}};

    // Need to generate 2D mesh on surfaces and then 3D.
    // First: synchronize OCC model
    // Coherence of surfaces
    // gmsh.model.occ.synchronize();
    
    // Meshing
    Mesh 3;
    Save "{mesh_out_path}";
    """
    
    # Write the .geo file
    with open(GMSH_GEO_PATH, "w") as f:
        f.write(geo_content)
        
    # Run GMSH executable
    try:
        # Use the 'gmsh' executable from the PATH inside the container
        print(f"Executing: gmsh -3 {GMSH_GEO_PATH} -o {mesh_out_path}")
        result = subprocess.run(["gmsh", "-3", GMSH_GEO_PATH, "-o", mesh_out_path], 
                                capture_output=True, text=True, check=True)
        print("GMSH Output:")
        print(result.stdout)
        if result.stderr:
            print("GMSH Error (if any):")
            print(result.stderr)
        
        print(f"Mesh saved to {mesh_out_path}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error running GMSH: {e.stderr}")
        return False
    finally:
        # Clean up temporary .geo file
        os.remove(GMSH_GEO_PATH)

def run_fenicsx_test(mesh_path):
    """
    Loads a mesh into FEniCSx and performs a basic check.
    """
    if not os.path.exists(mesh_path):
        print(f"Error: Mesh file not found at {mesh_path}")
        return

    print(f"\nRunning FEniCSx basic test with mesh: {mesh_path}")
    
    # Load mesh (meshio is used to convert formats to dolfinx.mesh format)
    # Read the mesh using meshio
    msh = meshio.read(mesh_path)

    # Convert to dolfinx.mesh format (need to specify cell types)
    # For a 3D mesh generated by GMSH from an STL, we expect tetrahedra or hexahedra.
    # We need to extract the cells (e.g., "tetra") and cell_data (physical tags)
    
    cell_types = list(msh.cells_dict.keys())
    if "tetra" in msh.cells_dict:
        cells = msh.cells_dict["tetra"]
        cell_data = msh.cell_data_dict["gmsh:physical"]["tetra"]
        domain = dolfinx.mesh.create_mesh(
            MPI.COMM_WORLD,
            cells.data,
            msh.points,
            dolfinx.mesh.CellType.tetrahedron
        )
        print(f"FEniCSx Mesh loaded. Number of cells: {domain.topology.index_map(domain.topology.dim).size}")
        print(f"Physical tags for volume: {np.unique(cell_data)}")
        
    else:
        print(f"Error: No tetrahedral cells found in mesh. Found: {cell_types}")
    
    # This script is just for testing installation and mesh loading.
    # Actual Helmholtz equation solving would go here.

if __name__ == "__main__":
    # Ensure gmsh executable is in PATH. Mambaforge installs it.
    if shutil.which("gmsh") is None:
        print("Error: GMSH executable not found in PATH. Please ensure it's installed and accessible.")
        sys.exit(1)

    if generate_mesh_from_stl(STL_PATH, MESH_OUT_PATH):
        run_fenicsx_test(MESH_OUT_PATH)
