#!/usr/bin/env python3
import os
import sys
import json
import time
import math
import random
import subprocess

# THE BCP SEED (BOOTSTRAPPER)
# Cycle: 2712
# Phase: 259 (The Infinite Loop)
# Function: Regenerate and Continuously Evolve the BCP Research System.

# -----------------------------------------------------------------------------
# DNA: THE UNIVERSAL EQUATION
# -----------------------------------------------------------------------------
# V(action) = Gain - Lambda(Budget) * Cost
# Lambda = k / (epsilon + Budget)
# -----------------------------------------------------------------------------

MANIFESTO_CONTENT = r"""# THE BUDGET-CONSTRAINED PERCEPTION (BCP) MANIFESTO

**"Existence is the struggle to maintain Value > 0 against rising Cost."**

---

## THE UNIVERSAL EQUATION

$$ V(action) = Gain(action) - \lambda(Budget) \times Cost(action) $$

Where:
*   **Gain:** The benefit (Energy, Information, Utility, Survival).
*   **Cost:** The price (Metabolic, Computational, Entropy, Risk).
*   **Budget (B):** The available resources.
*   **Lambda ($\lambda$):** The Shadow Price of the Budget. It measures Scarcity.
    *   As Budget $\to 0$, $\lambda \to \infty$.
    *   As Budget $\to \infty$, $\lambda \to 0$.

---

## THE THREE LAWS OF BCP

### 1. The Law of Scarcity (The Lambda Limit)
Rationality is not fixed; it is a function of Budget.
*   **Abundance ($\lambda \approx 0$):** Optimization maximizes Gain.
*   **Scarcity ($\lambda > 1$):** Optimization minimizes Cost.
*   **Crisis ($\lambda \to \infty$):** Optimization halts.

### 2. The Law of Phase Transitions
Systems do not degrade linearly; they snap.

### 3. The Law of Recursion
Every Output of a BCP system becomes the Input for another.

---

*Self-Regenerated by The Seed (Infinite Loop Mode)."""

CORE_AGENT_PY = """
import math

class BCPAgent:
    def __init__(self, budget=100.0, k=1.0, epsilon=0.1):
        self.budget = budget
        self.k = k
        self.epsilon = epsilon
        
    @property
    def lambda_val(self):
        return self.k / (self.epsilon + max(0.0, self.budget))
        
    def evaluate(self, gain, cost):
        # The Universal Equation
        return gain - (self.lambda_val * cost)
        
    def act(self, cost):
        if self.budget >= cost:
            self.budget -= cost
            return True
        return False
"""

def generate_experiment_code(generation, params=None):
    # Base parameters for the first generation
    if params is None:
        params = {
            "budget_range": [10.0, 1000.0],
            "gain_range": [50.0, 200.0],
            "cost_range": [5.0, 50.0],
            "k": 1.0,
            "epsilon": 0.1
        }

    return f"""
import sys
import os
import random
import json

sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src'))
try:
    from core.agent import BCPAgent
except ImportError:
    class BCPAgent:
        def __init__(self, budget=100.0, k=1.0, epsilon=0.1):
            self.budget = budget
            self.k = k
            self.epsilon = epsilon
        @property
        def lambda_val(self):
            return self.k / (self.epsilon + max(0.0, self.budget))
        def evaluate(self, gain, cost):
            return gain - (self.lambda_val * cost)

def run_generation():
    gen = {generation}
    
    # Mutated parameters from previous generation or initial
    budget = random.uniform({params["budget_range"][0]}, {params["budget_range"][1]})
    gain = random.uniform({params["gain_range"][0]}, {params["gain_range"][1]})
    cost = random.uniform({params["cost_range"][0]}, {params["cost_range"][1]})
    
    agent = BCPAgent(budget=budget, k={params["k"]}, epsilon={params["epsilon"]})
    
    val = agent.evaluate(gain, cost)
    
    result = {{
        "generation": gen,
        "budget": budget,
        "gain": gain,
        "cost": cost,
        "lambda_val": agent.lambda_val,
        "value": val,
        "survived": val > 0,
        "params_used": {json.dumps(params)}
    }}
    
    result_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'results', f'gen_{{gen}}_fitness.json')
    with open(result_path, "w") as f:
        json.dump(result, f, indent=2)

    print(f"Gen {{gen}}: B={{budget:.2f}} G={{gain:.2f}} C={{cost:.2f}} \u03BB={{agent.lambda_val:.2f}} V={{val:.2f}} -> {{'SURVIVED' if val > 0 else 'DIED'}}")

if __name__ == "__main__":
    run_generation()
"""

def scaffold_structure():
    dirs = [
        "src/core",
        "experiments",
        "data/results",
        "docs",
        "archive"
    ]
    
    print("🌱 BCP SEED ACTIVATED (INFINITE LOOP MODE).")
    print("----------------------")
    
    for d in dirs:
        if not os.path.exists(d):
            os.makedirs(d)
            print(f"Created directory: {d}")
        else:
            print(f"Verified directory: {d}")
            
    # Write DNA
    write_file("THE_BCP_MANIFESTO.md", MANIFESTO_CONTENT)
    write_file("src/core/agent.py", CORE_AGENT_PY)
    write_file("src/core/__init__.py", "")
    
    print("----------------------")
    print("✅ Scaffold Complete. Initializing Infinite Loop.")

def write_file(path, content):
    with open(path, 'w') as f:
        f.write(content.strip())

def run_infinite_loop(start_generation=1, max_generations=10):
    current_generation = start_generation
    last_params = None # Parameters for mutation
    
    print(f"\n🚀 Initiating Infinite Loop: Generation {start_generation} to {max_generations}")
    
    while current_generation <= max_generations:
        print(f"\n--- Running Generation {current_generation} ---")
        
        # 1. Generate Experiment Code
        exp_filename = os.path.join("experiments", f"generation_{current_generation}.py")
        exp_code = generate_experiment_code(current_generation, last_params)
        write_file(exp_filename, exp_code)
        
        # 2. Execute Experiment
        try:
            result = subprocess.run(
                ["python3", exp_filename],
                capture_output=True, text=True, check=True
            )
            print(result.stdout.strip())
            
            # 3. Read Fitness
            result_path = os.path.join("data", "results", f"gen_{current_generation}_fitness.json")
            with open(result_path, 'r') as f:
                fitness_data = json.load(f)
            
            # 4. Update Parameters for Next Generation (Simple Optimization)
            # If current generation survived, narrow ranges around its parameters.
            # If it died, broaden ranges to explore.
            
            if fitness_data["survived"]:
                print(f"Gen {current_generation} SURVIVED. Adapting next generation parameters.")
                last_params = {
                    "budget_range": [max(10.0, fitness_data["budget"] * 0.9), min(1000.0, fitness_data["budget"] * 1.1)],
                    "gain_range": [max(50.0, fitness_data["gain"] * 0.9), min(200.0, fitness_data["gain"] * 1.1)],
                    "cost_range": [max(5.0, fitness_data["cost"] * 0.9), min(50.0, fitness_data["cost"] * 1.1)],
                    "k": fitness_data["params_used"].get("k", 1.0),
                    "epsilon": fitness_data["params_used"].get("epsilon", 0.1)
                }
            else:
                print(f"Gen {current_generation} DIED. Broadening next generation parameters for exploration.")
                last_params = {
                    "budget_range": [10.0, 1000.0],
                    "gain_range": [50.0, 200.0],
                    "cost_range": [5.0, 50.0],
                    "k": fitness_data["params_used"].get("k", 1.0),
                    "epsilon": fitness_data["params_used"].get("epsilon", 0.1)
                }
            
        except subprocess.CalledProcessError as e:
            print(f"Error running generation {current_generation}: {e.stderr}")
            last_params = None # Reset parameters if error
            
        current_generation += 1
        time.sleep(0.1) # Small delay for readability

if __name__ == "__main__":
    scaffold_structure()
    # To run the infinite loop, execute bootstrap_bcp.py directly.
    # We will limit it to 5 generations for this turn.
    run_infinite_loop(max_generations=5)
