#!/usr/bin/env python3
import os
import sys
import json
import time
import math

# THE BCP SEED (BOOTSTRAPPER)
# Cycle: 2702
# Phase: 256 (The Seed)
# Function: Regenerate the Budget-Constrained Perception (BCP) Research System from Zero.

# -----------------------------------------------------------------------------
# DNA: THE UNIVERSAL EQUATION
# -----------------------------------------------------------------------------
# V(action) = Gain - Lambda(Budget) * Cost
# Lambda = k / (epsilon + Budget)
# -----------------------------------------------------------------------------

MANIFESTO_CONTENT = r"""# THE BUDGET-CONSTRAINED PERCEPTION (BCP) MANIFESTO

**"Existence is the struggle to maintain Value > 0 against rising Cost."**

---

## THE UNIVERSAL EQUATION

$$ V(action) = Gain(action) - \lambda(Budget) \times Cost(action) $$

Where:
*   **Gain:** The benefit (Energy, Information, Utility, Survival).
*   **Cost:** The price (Metabolic, Computational, Entropy, Risk).
*   **Budget (B):** The available resources.
*   **Lambda ($\lambda$):** The Shadow Price of the Budget. It measures Scarcity.
    *   As Budget $\to 0$, $\lambda \to \infty$.
    *   As Budget $\to \infty$, $\lambda \to 0$.

---

## THE THREE LAWS OF BCP

### 1. The Law of Scarcity (The Lambda Limit)
Rationality is not fixed; it is a function of Budget.
*   **Abundance ($\\lambda \approx 0$):** Optimization maximizes Gain.
*   **Scarcity ($\\lambda > 1$):** Optimization minimizes Cost.
*   **Crisis ($\\lambda \to \infty$):** Optimization halts.

### 2. The Law of Phase Transitions
Systems do not degrade linearly; they snap.

### 3. The Law of Recursion
Every Output of a BCP system becomes the Input for another.

---

*Self-Regenerated by The Seed.*
"""

CORE_AGENT_PY = """
import math

class BCPAgent:
    def __init__(self, budget=100.0, k=1.0, epsilon=0.1):
        self.budget = budget
        self.k = k
        self.epsilon = epsilon
        
    @property
    def lambda_val(self):
        return self.k / (self.epsilon + max(0.0, self.budget))
        
    def evaluate(self, gain, cost):
        # The Universal Equation
        return gain - (self.lambda_val * cost)
        
    def act(self, cost):
        if self.budget >= cost:
            self.budget -= cost
            return True
        return False
"""

EXPERIMENT_TEMPLATE_PY = """
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src'))
try:
    from core.agent import BCPAgent
except ImportError:
    # Fallback if running isolated
    class BCPAgent:
        def __init__(self, budget=100.0, k=1.0, epsilon=0.1):
            self.budget = budget
            self.k = k
            self.epsilon = epsilon
        @property
        def lambda_val(self):
            return self.k / (self.epsilon + max(0.0, self.budget))
        def evaluate(self, gain, cost):
            return gain - (self.lambda_val * cost)

def run_experiment():
    print("Running BCP Regeneration Experiment...")
    agent = BCPAgent(budget=10.0)
    
    # Scenario: High Cost, High Gain
    gain = 100.0
    cost = 5.0
    
    val = agent.evaluate(gain, cost)
    print(f"Budget: {agent.budget}, Lambda: {agent.lambda_val:.2f}")
    print(f"Action(G={gain}, C={cost}) -> Value: {val:.2f}")
    
    if val > 0:
        print("Action TAKEN.")
    else:
        print("Action REJECTED.")

if __name__ == "__main__":
    run_experiment()
"""

def scaffold_structure():
    dirs = [
        "src/core",
        "experiments",
        "data/results",
        "docs",
        "archive"
    ]
    
    print("🌱 BCP SEED ACTIVATED.")
    print("----------------------")
    
    for d in dirs:
        if not os.path.exists(d):
            os.makedirs(d)
            print(f"Created directory: {d}")
        else:
            print(f"Verified directory: {d}")
            
    # Write DNA
    write_file("THE_BCP_MANIFESTO.md", MANIFESTO_CONTENT)
    write_file("src/core/agent.py", CORE_AGENT_PY)
    write_file("src/core/__init__.py", "")
    write_file("experiments/cycle001_regeneration.py", EXPERIMENT_TEMPLATE_PY)
    
    print("----------------------")
    print("✅ Scaffold Complete. System Ready for Recursion.")

def write_file(path, content):
    with open(path, 'w') as f:
        f.write(content.strip())
    print(f"Wrote DNA to: {path}")

if __name__ == "__main__":
    scaffold_structure()