# Dockerfile for FEniCSx (DOLFINx) in Duality-Zero using Mambaforge

# Use mambaforge as a base image for easy conda environment management
FROM condaforge/mambaforge:latest

# Set environment variables
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH="/opt/conda/bin:$PATH"

# Install FEniCSx (dolfinx) and its dependencies using mamba
# This will handle PETSc/SLEPc compilation or use pre-compiled versions
RUN mamba create -n fenicsx-env -y \
    python=3.10 \
    fenics-dolfinx=0.7.0 \
    mpi4py \
    petsc4py \
    slepc4py \
    meshio \
    gmsh \
    matplotlib \
    numpy \
    scipy \
    && mamba clean -af

# Activate the created environment
# Add a command to activate the environment when the container starts
SHELL ["conda", "run", "-n", "fenicsx-env", "/bin/bash", "-c"]

# Set a working directory inside the container
WORKDIR /app

# Command to run when the container starts (can be overridden)
CMD ["conda", "run", "-n", "fenicsx-env", "/bin/bash"]

# Add a note on how to build this image:
# docker build -t duality-fenicsx .
#
# How to run:
# docker run -ti --rm -v /Volumes/dual/DUALITY-ZERO-V2:/app duality-fenicsx /bin/bash