/* THE COMMONS — the name table. Data only; commons/names.html is the surface,
 * commons/commons.js is the engine all three surfaces share.
 *
 * WHAT THIS IS. One OBJECT, every name the field says for it, and the one name to
 * write on the order. A man gets handed a word by somebody from another trade,
 * another region or another counter, and either he knows it or the wrong thing
 * shows up on the truck. Nobody owns this document, which is why it does not
 * exist anywhere else.
 *
 * WHAT THIS IS NOT — AND THIS IS THE WHOLE SAFETY DESIGN. It is not a spec, not a
 * catalog, and not authority about the OBJECT. It is evidence about the WORD, and
 * it will be read as authority about the object anyway, so the guard lives in the
 * data shape rather than in the copy:
 *
 *   n   THE ORDER NAME. The plain generic, and the only string on the row that a
 *       man should write down. Never a trademark.
 *   o   THE OBJECT, declared in one clause a reviewer can hold against the alias
 *       list and say yes or no to. A row without it is a word with no referent.
 *   a   what the field says, each with WHO SAYS IT and a KIND — and the kind, not
 *       the writer, decides the framing on the page:
 *         tm  → "a brand people say"   (never what to write on the order)
 *         reg → "you might hear"       (never "it is called")
 *         say → "the field says"
 *         sup → "the counter says"
 *   no  the near-miss guard. The rows that earn this page are the ones where the
 *       wrong word gets the wrong OBJECT walked over to you, which is a different
 *       failure from not knowing the word at all.
 *
 * NO NUMBERS, ANYWHERE. Not in a name, not in an object clause, not in a guard.
 * A row may not separate near-names by size, depth, gang, gauge or rating —
 * a name that needs a number to be right is certified data we do not ship, and
 * the gate fails the build on a single digit.
 *
 * IT IS ALSO AN INDEX, and that is the reason it is not a glossary. Every alias
 * here is searchable from the OTHER commons surfaces through shared/find.js:
 * type "stinger" into the gear list and the extension cord comes up, though that
 * word appears nowhere in gear.js. commons.js §THE ALIAS INDEX has the join, the
 * deploy counts it, and tools/toolkit-gates/commons-names.mjs derives a routing
 * probe from every alias that is not already on the gear page.
 *
 * PROVENANCE. Seeded 2026-08-14 by a fan-out — one vocabulary pass per trade pair
 * plus a universal pass, ninety-eight candidates — then cut by three independent
 * adversarial lenses: a rails reviewer holding the list above, a journeyman
 * rejecting slang from a video rather than a jobsite, and a partition reviewer
 * owning the tags and killing rows nobody would ever type. The seed is the floor,
 * not the ceiling: every shop and region has its own word, and a correction from
 * someone who does the work outranks anything here.
 *
 * Author: Aldrin Payopay <aldrin.gdf@gmail.com>
 */

window.COMMONS_NAMES = [
  /* ---- the floor: every trade on the job says these ------------------ */
  { id: "extension-cord", n: "Extension cord", t: ["universal"],
    o: "A run of flexible cord with a plug on one end and a socket on the other.",
    a: [{ n: "stinger", by: "film, video and live-event crews", k: "say" },
        { n: "extension lead", by: "UK, Ireland, Australia and New Zealand hands", k: "reg" },
        { n: "drop cord", by: "the South", k: "reg" },
        { n: "cord set", by: "the counter and the catalog", k: "sup" }],
    no: "A drop light — the caged work lamp on a cord that some shops also call a drop cord." },
  { id: "adjustable-wrench", n: "Adjustable wrench", t: ["universal"],
    o: "A wrench with one fixed jaw and one smooth jaw a worm screw slides open.",
    a: [{ n: "Crescent wrench", by: "most of the US — a brand that ate the category", k: "tm" },
        { n: "C-wrench", by: "film, video and live-event crews", k: "say" },
        { n: "adjustable spanner", by: "UK and Ireland hands", k: "reg" },
        { n: "shifter", by: "Australia and New Zealand hands", k: "reg" },
        { n: "knuckle buster", by: "older hands, and never kindly", k: "say" }],
    no: "A pipe wrench — hardened toothed jaws that bite round pipe. Older hands call both a monkey wrench, and the pipe wrench is the one that turns up." },
  { id: "tape-measure", n: "Tape measure", t: ["universal"],
    o: "A curved steel blade on a spring return in a case, sliding hook on the end.",
    a: [{ n: "tape", by: "everybody on site — though on a set it means the roll", k: "say" },
        { n: "tape rule", by: "the counter and the catalog", k: "sup" },
        { n: "measuring tape", by: "outside the trades, and plenty inside them", k: "say" }],
    no: "Gaffer tape — say hand me the tape on a set and the roll is what arrives." },
  { id: "dikes", n: "Diagonal cutters", t: ["universal"],
    o: "Pliers whose jaws are two cutting edges set across the handles, with no gripping face.",
    a: [{ n: "dikes", by: "North American electricians and installers; some write it dykes", k: "say" },
        { n: "side cutters", by: "Canada, and a lot of electricians", k: "say" },
        { n: "nippers", by: "UK and Ireland hands, and old-timers", k: "reg" },
        { n: "snips", by: "some shops — and it means sheet metal shears in others", k: "say" },
        { n: "wire cutters", by: "the counter, and everybody outside the trade", k: "sup" }],
    no: "Tin snips — the long shear-handled ones for sheet metal, which many shops call snips." },
  { id: "cable-ties", n: "Cable ties", t: ["universal"],
    o: "A toothed nylon strap with a ratchet head that grips the teeth and will not back off.",
    a: [{ n: "zip ties", by: "everybody", k: "say" },
        { n: "zap straps", by: "British Columbia and West Coast crews", k: "reg" },
        { n: "tie wraps", by: "older electricians", k: "say" },
        { n: "Ty-Rap", by: "electricians, for the steel-barb ones", k: "tm" },
        { n: "wire ties", by: "the supply counter", k: "sup" }],
    no: "Hook-and-loop cable wrap, the reusable fabric strap with no ratchet head on it." },
  { id: "utility-knife", n: "Utility knife", t: ["universal"],
    o: "A metal-handled knife holding a short replaceable blade, most of them retractable.",
    a: [{ n: "box cutter", by: "most of the field, and the only word some crews use", k: "say" },
        { n: "Stanley knife", by: "the UK, Ireland, Australia, and older hands anywhere — it is a brand", k: "tm" },
        { n: "razor knife", by: "the field, mostly older hands", k: "say" }],
    no: "A snap-off knife — the long segmented blade you break back a piece at a time." },
  { id: "marker", n: "Permanent marker", t: ["universal"],
    o: "A felt-tipped pen carrying solvent ink instead of water-based ink.",
    a: [{ n: "Sharpie", by: "almost everybody in North America — it is a brand", k: "tm" },
        { n: "Magic Marker", by: "older hands — also a brand", k: "tm" },
        { n: "texta", by: "Australian and New Zealand crews", k: "reg" },
        { n: "felt pen", by: "Canada, the UK and Ireland", k: "reg" }],
    no: "A lumber crayon (keel) — wax in a paper wrap, for wet concrete and dirty steel." },
  { id: "headlamp", n: "Headlamp", t: ["universal"],
    o: "A small lamp on an elastic band or a hat clip, carrying its own battery.",
    a: [{ n: "head torch", by: "the UK, Ireland, Australia and New Zealand", k: "reg" },
        { n: "headlight", by: "plenty of hands on site", k: "say" },
        { n: "cap lamp", by: "mining-side crews and some Canadian shops", k: "reg" }],
    no: "A vehicle headlight — what a parts counter hears when you say headlight." },
  { id: "step-ladder", n: "Step ladder", t: ["universal"],
    o: "A folding ladder hinged to its own back legs, standing without leaning on anything.",
    a: [{ n: "A-frame", by: "film, video and live-event crews, and plenty of framers", k: "say" },
        { n: "steps", by: "the UK and Ireland — a pair of steps", k: "reg" }],
    no: "A hop-up — the low fold-out platform you stand on, which is not a ladder." },
  /* ---- av ------------------------------------------------------------ */
  { id: "tone-generator-probe", n: "Tone generator & probe", t: ["low-voltage", "electrical", "av"],
    o: "A pocket box that puts a warble on a dead pair, plus a wand that hears it through the jacket.",
    a: [{ n: "toner", by: "cabling techs", k: "say" },
        { n: "Fox and Hound", by: "cabling and phone techs, on any brand of kit", k: "tm" },
        { n: "the banana", by: "cabling techs, for the probe", k: "say" },
        { n: "tone and probe", by: "the supply counter", k: "sup" },
        { n: "inductive amplifier", by: "the supply counter", k: "sup" },
        { n: "buzzer", by: "phone men", k: "say" }],
    no: "A circuit tracer for live branch circuits, which rides on power and finds breakers, not pairs." },
  { id: "impact-punch-down-tool", n: "Impact punch-down tool", t: ["low-voltage", "av"],
    o: "A spring-loaded handle that seats a conductor into a slotted contact and trims the tail in the same stroke.",
    a: [{ n: "punchdown", by: "cabling techs", k: "say" },
        { n: "punch tool", by: "cabling techs", k: "say" },
        { n: "Krone tool", by: "British and Australian techs", k: "tm" },
        { n: "impact tool", by: "the supply counter", k: "sup" }],
    no: "A seating stick with no impact in it, which pushes the wire home but will not cut the tail off." },
  { id: "coax-compression", n: "Coax compression tool", t: ["low-voltage", "av"],
    o: "A hand press that seats a one-piece connector onto prepared coax in a single squeeze.",
    a: [{ n: "compression tool", by: "cable and camera techs", k: "say" },
        { n: "Snap-N-Seal", by: "cable techs", k: "tm" },
        { n: "coax crimpers", by: "many techs, though it presses rather than crimps", k: "say" },
        { n: "F-connector tool", by: "the supply counter", k: "sup" }],
    no: "A hex crimper for the old crimp-on sleeve ends, which squashes a ferrule rather than pressing a body on." },
  { id: "low-voltage-mounting-bracket", n: "Low-voltage mounting bracket", t: ["low-voltage", "av"],
    o: "An open frame that carries a wall plate with no box behind it, so cable passes straight through.",
    a: [{ n: "mud ring", by: "cabling and AV techs, meaning a different thing than an electrician means", k: "say" },
        { n: "LV ring", by: "cabling and AV techs", k: "say" },
        { n: "open-back ring", by: "the supply counter", k: "sup" },
        { n: "old-work bracket", by: "the supply counter", k: "sup" },
        { n: "Caddy bracket", by: "low-voltage installers, brand or not", k: "tm" }],
    no: "A plaster ring — the steel ring that bolts onto an electrician's box. Same nickname, different part." },
  { id: "gaffer-tape", n: "Gaffer tape", t: ["creative", "av"],
    o: "Matte cloth tape with a coated back that tears by hand and peels up without leaving glue.",
    a: [{ n: "gaff", by: "crews everywhere", k: "say" },
        { n: "gaffa", by: "crews in the UK and Australia", k: "reg" },
        { n: "cloth tape", by: "the supply counter", k: "sup" }],
    no: "Camera tape — the narrower matte roll an AC buys by the case, ordered on its own line. And duct tape, which leaves its glue behind." },
  { id: "duvetyne", n: "Duvetyne", t: ["creative", "av"],
    o: "Dull black napped cotton cloth sold off the roll, with no sheen on the face.",
    a: [{ n: "duvy", by: "grips", k: "say" },
        { n: "commando cloth", by: "the rental and expendables counter", k: "sup" },
        { n: "molton", by: "theatre and event crews in Europe", k: "reg" }],
    no: "Blackout curtain lining — the coated, white-backed drapery fabric from a fabric shop." },
  { id: "intercom-beltpack", n: "Intercom beltpack", t: ["av", "creative"],
    o: "A belt-worn box with a headset jack and a talk button, wired into the crew's talk line.",
    a: [{ n: "comms", by: "event and broadcast crews", k: "say" },
        { n: "beltpack", by: "most crews", k: "say" },
        { n: "Clear-Com", by: "event and broadcast crews, on any brand of kit", k: "tm" }],
    no: "A walkie-talkie — the handheld radio a film crew means when it says comms." },
  { id: "hole-cutter", n: "Adjustable hole cutter", t: ["av"],
    o: "A rotating arm carrying a sliding cutter blade around a pilot bit, set by hand to the circle wanted.",
    a: [{ n: "circle cutter", by: "installers", k: "say" },
        { n: "fly cutter", by: "installers and woodworkers", k: "say" },
        { n: "speaker cutter", by: "AV installers", k: "say" },
        { n: "adjustable hole saw", by: "the supply counter", k: "sup" }],
    no: "A machinist's fly cutter — a milling-machine tool of the same name, for a mill, not a ceiling." },
  { id: "console-cable", n: "Console cable", t: ["av", "low-voltage"],
    o: "A flat cable wired end-for-end reversed, for talking to a switch or a device's serial port.",
    a: [{ n: "rollover cable", by: "network and AV techs", k: "say" },
        { n: "the blue cable", by: "network and AV techs", k: "say" },
        { n: "Cisco cable", by: "techs on any brand of kit", k: "tm" },
        { n: "console lead", by: "the supply counter", k: "sup" }],
    no: "A straight-through patch cable — same connectors, wired the other way, and it will not talk to the console port." },
  { id: "diffusion-gel", n: "Diffusion gel", t: ["creative", "av"],
    o: "A milky translucent plastic sheet, sold by the sheet or the roll, cut to fit a lamp's gel frame.",
    a: [{ n: "diff", by: "film lighting crews", k: "say" },
        { n: "frost", by: "theatre and event lighting crews", k: "say" },
        { n: "gel", by: "lighting crews, colour or not", k: "say" },
        { n: "Rosco", by: "lighting crews, brand or not", k: "tm" },
        { n: "Lee", by: "lighting crews in the UK", k: "tm" }],
    no: "Colour gel — the same sheet stock in a colour, which tints the light instead of softening it." },
  { id: "lavalier-microphone", n: "Lavalier microphone", t: ["av", "creative"],
    o: "A pea-sized microphone on a thin captive cable, clipped to clothing or taped to skin.",
    a: [{ n: "lav", by: "film and TV sound crews", k: "say" },
        { n: "lapel mic", by: "corporate AV crews", k: "say" },
        { n: "body mic", by: "theatre and house-of-worship crews", k: "say" }],
    no: "The bodypack transmitter it plugs into — that is the radio, not the microphone." },
  { id: "stage-monitor-speaker", n: "Stage monitor speaker", t: ["av", "creative"],
    o: "A wedge-shaped loudspeaker cabinet that sits on the deck and fires up at whoever is standing there.",
    a: [{ n: "wedge", by: "live-sound crews", k: "say" },
        { n: "monitor", by: "audio crews", k: "say" },
        { n: "foldback", by: "crews in the UK and Australia", k: "reg" },
        { n: "floor monitor", by: "the rental counter", k: "sup" }],
    no: "A video monitor — ask the AV crew in the same room for a monitor and a screen on a stand arrives." },
  { id: "audio-snake", n: "Audio snake", t: ["av", "creative"],
    o: "A single thick jacketed cable carrying many audio lines, fanning out to connectors at each end.",
    a: [{ n: "snake", by: "live-sound crews", k: "say" },
        { n: "multicore", by: "crews in the UK and Europe", k: "reg" },
        { n: "loom", by: "crews in the UK and Australia", k: "reg" },
        { n: "multipair", by: "the cable counter", k: "sup" }],
    no: "A wire-pulling fish tape — the steel snake an electrician hands over when you ask for a snake." },
  /* ---- plumbing ------------------------------------------------------ */
  { id: "tongue-and-groove-pliers", n: "Tongue-and-groove pliers", t: ["plumbing", "hvac", "electrical", "gc"],
    o: "Pliers whose lower jaw slides along a grooved track cut into the handle.",
    a: [{ n: "Channellocks", by: "nearly everyone on site, plumbers first", k: "tm" },
        { n: "water pump pliers", by: "the counter, and most of Britain", k: "sup" },
        { n: "multi-grips", by: "Australian and Kiwi trades", k: "reg" },
        { n: "groove joints", by: "the field", k: "say" }],
    no: "Slip-joint pliers — the small household pair with a short notched pivot, not a grooved track." },
  { id: "cast-in-sleeve", n: "Cast-in sleeve", t: ["concrete", "plumbing", "electrical"],
    o: "A length of pipe or a purpose-made tube set in the forms before the pour, left hollow.",
    a: [{ n: "sleeve", by: "everybody on the floor", k: "say" },
        { n: "penetration", by: "GCs and PMs", k: "say" },
        { n: "thimble", by: "some shops and older prints", k: "say" },
        { n: "wall sleeve", by: "the counter", k: "sup" }],
    no: "A blockout — a boxed void framed into the pour and stripped out after. Not a tube left in it." },
  { id: "pipe-wrenches", n: "Pipe wrenches", t: ["plumbing", "hvac"],
    o: "Wrench with hardened toothed jaws that bite round pipe and tighten as you pull.",
    a: [{ n: "Stillson", by: "British and Irish trades", k: "tm" },
        { n: "Stillie", by: "Irish and Scottish hands", k: "reg" },
        { n: "pipe grips", by: "British counters", k: "sup" },
        { n: "monkey wrench", by: "older North American hands, loosely", k: "say" }],
    no: "Monkey wrench — flat smooth parallel jaws, no teeth; it spins on round pipe." },
  { id: "closet-auger", n: "Closet auger", t: ["plumbing"],
    o: "Short cable inside a rigid bent tube with a sleeve over the bend, cranked by hand.",
    a: [{ n: "toilet auger", by: "the counter and most of the trade", k: "sup" },
        { n: "closet snake", by: "the field", k: "say" },
        { n: "bowl auger", by: "catalogues", k: "sup" }],
    no: "Hand drum auger — a long cable in a canister, no rigid bend and no sleeve on it." },
  { id: "hand-drum-auger", n: "Hand drum auger", t: ["plumbing"],
    o: "Coiled spring steel cable stored in a hand-cranked drum and fed out by hand.",
    a: [{ n: "snake", by: "everybody", k: "say" },
        { n: "hand snake", by: "the field, said against a machine", k: "say" },
        { n: "canister auger", by: "the counter", k: "sup" },
        { n: "plumber's snake", by: "the counter and the customer", k: "sup" }],
    no: "Drain rods — rigid screw-together sticks with a plunger or corkscrew head, not a coiled cable." },
  { id: "thread-seal-tape", n: "Thread seal tape", t: ["plumbing", "hvac"],
    o: "Thin plastic film tape with no adhesive on it, wound on a small spool.",
    a: [{ n: "Teflon tape", by: "nearly everyone", k: "tm" },
        { n: "PTFE tape", by: "British and Australian counters", k: "sup" },
        { n: "plumber's tape", by: "the field", k: "say" },
        { n: "thread tape", by: "the counter", k: "sup" },
        { n: "pipe tape", by: "the field", k: "say" }],
    no: "Perforated hanger strap — punched metal banding, also called plumber's tape." },
  { id: "perforated-hanger-strap", n: "Perforated hanger strap", t: ["plumbing", "hvac"],
    o: "Coil of thin metal banding punched with holes the whole way down its length.",
    a: [{ n: "plumber's tape", by: "the field", k: "say" },
        { n: "band iron", by: "the field", k: "say" },
        { n: "banding", by: "the field", k: "say" },
        { n: "hanger iron", by: "older hands", k: "say" },
        { n: "hanger strap", by: "the counter", k: "sup" }],
    no: "Thread seal tape — the plastic film on a spool, also called plumber's tape." },
  { id: "closet-flange", n: "Closet flange", t: ["plumbing"],
    o: "Collar fitting that lands on the floor over the drain, carrying slotted bolt tracks.",
    a: [{ n: "toilet flange", by: "the counter and most of the trade", k: "sup" },
        { n: "closet ring", by: "the field", k: "say" },
        { n: "floor flange", by: "the field", k: "say" }],
    no: "Floor flange — a threaded pipe fitting with bolt holes, for standing pipe off a surface." },
  { id: "air-admittance-valve", n: "Air admittance valve", t: ["plumbing"],
    o: "Vent fitting holding a light rubber flap that lifts on suction and drops shut.",
    a: [{ n: "Studor", by: "North American trades", k: "tm" },
        { n: "Durgo", by: "British and Irish trades", k: "tm" },
        { n: "cheater vent", by: "the field", k: "say" },
        { n: "AAV", by: "the counter", k: "sup" }],
    no: "Roof vent cap — the open hood sitting over the vent stack, nothing moving inside it." },
  { id: "fixture-supply-line", n: "Fixture supply line", t: ["plumbing"],
    o: "Short flexible tube carrying a nut on each end, joining a stop to a fixture.",
    a: [{ n: "riser", by: "the field", k: "say" },
        { n: "supply tube", by: "the counter", k: "sup" },
        { n: "flex line", by: "the field", k: "say" },
        { n: "flexi", by: "British and Australian trades", k: "reg" },
        { n: "tap connector", by: "British counters", k: "sup" },
        { n: "closet supply", by: "the counter", k: "sup" }],
    no: "Riser — the vertical water main climbing to the floors above. Same word, different object." },
  { id: "flare-nut-wrench", n: "Flare nut wrench", t: ["hvac", "plumbing"],
    o: "Box wrench with the ring cut open along a slot so it passes over tubing.",
    a: [{ n: "line wrench", by: "the field", k: "say" },
        { n: "tubing wrench", by: "the counter", k: "sup" },
        { n: "flare wrench", by: "the field", k: "say" },
        { n: "brake line wrench", by: "auto counters", k: "sup" }],
    no: "Open-end wrench — an open jaw gripping opposite faces only, no ring around the nut." },
  { id: "phos-copper-brazing-rod", n: "Phos-copper brazing rod", t: ["hvac", "plumbing"],
    o: "Stiff bare rod of copper and phosphorus alloy, melted into a copper joint at torch heat.",
    a: [{ n: "Sil-Fos", by: "refrigeration hands", k: "tm" },
        { n: "Stay-Silv", by: "refrigeration hands", k: "tm" },
        { n: "silver", by: "the field", k: "say" },
        { n: "silver solder", by: "the field", k: "say" },
        { n: "brazing alloy", by: "the counter", k: "sup" }],
    no: "Soft solder wire on a spool — a different alloy, sweated with a plumbing torch." },
  /* ---- electrical ---------------------------------------------------- */
  { id: "linemans-pliers", n: "Lineman's pliers", t: ["electrical"],
    o: "Heavy squared-off pliers with a flat gripping nose and side cutters set into the same jaws.",
    a: [{ n: "Kleins", by: "electricians everywhere", k: "tm" },
        { n: "side cutters", by: "electricians — though to a Canadian or an Australian it means the dikes", k: "say" },
        { n: "linesman pliers", by: "electricians who spell it that way, and most catalogs", k: "say" },
        { n: "combination pliers", by: "British and Australian sparkies", k: "reg" }],
    no: "Diagonal cutting pliers, the dikes, which only cut and have no flat gripping nose." },
  { id: "non-contact-voltage-tester", n: "Non-contact voltage tester", t: ["electrical", "low-voltage"],
    o: "A pen-sized plastic wand with a lamp and a buzzer in the tip, carrying its own battery and no test leads.",
    a: [{ n: "tick tracer", by: "electricians", k: "tm" },
        { n: "VoltAlert", by: "service techs", k: "tm" },
        { n: "volt pen", by: "electricians", k: "say" },
        { n: "sniffer", by: "electricians", k: "say" }],
    no: "A solenoid voltage tester, the heavy one with a pair of leads that buzzes and kicks in your hand. Plenty of men say tester for that." },
  { id: "powder-tool", n: "Powder-actuated fastening tool", t: ["framing", "electrical", "hvac"],
    o: "A pistol-gripped steel tool with a barrel, taking a hardened pin at the muzzle and a powder cartridge behind it.",
    a: [{ n: "Hilti gun", by: "most crews, whoever made the one in the case", k: "tm" },
        { n: "Ramset", by: "older crews and the rental counter", k: "tm" },
        { n: "powder gun", by: "the field", k: "say" },
        { n: "powder-actuated nailer", by: "the rental counter", k: "sup" }],
    no: "A pneumatic framing nailer — air and nails, and it does nothing to concrete." },
  { id: "clamp-meter", n: "Clamp meter", t: ["electrical"],
    o: "A hand meter with a hinged jaw that closes around a conductor, readout built into the handle.",
    a: [{ n: "amp clamp", by: "electricians", k: "say" },
        { n: "Amprobe", by: "old hands and service men", k: "tm" },
        { n: "clamp-on", by: "electricians", k: "say" },
        { n: "tong tester", by: "utility crews and older shops", k: "say" },
        { n: "clamp-on ammeter", by: "the supply counter", k: "sup" }],
    no: "A bare current probe that clips on but carries no display, it only feeds a separate meter." },
  { id: "fish-tape", n: "Fish tape", t: ["electrical", "low-voltage"],
    o: "A long flat springy band wound on a reel, fed through conduit to draw wire back.",
    a: [{ n: "snake", by: "electricians and everyone else", k: "say" },
        { n: "fish wire", by: "older residential men", k: "say" },
        { n: "steel fish", by: "the supply counter", k: "sup" }],
    no: "A drain snake, the plumber's coiled cable auger. Say snake on a mixed job and that is what walks over." },
  { id: "armored-cable-cutter", n: "Armored cable cutter", t: ["electrical"],
    o: "A hand-cranked cutter with a small saw wheel that scores across the spiral metal jacket.",
    a: [{ n: "Roto-Split", by: "electricians", k: "tm" },
        { n: "BX cutter", by: "electricians", k: "say" },
        { n: "cable stripper", by: "the supply counter", k: "sup" }],
    no: "A round-cable jacket stripper, the small rotating ring tool for plastic-jacketed cable, no saw wheel in it." },
  { id: "twist-on-wire-connector", n: "Twist-on wire connector", t: ["electrical"],
    o: "A plastic cap with a tapered metal spring inside that twists down onto stripped conductor ends.",
    a: [{ n: "Marrette", by: "Canadian electricians", k: "tm" },
        { n: "wire nut", by: "American electricians", k: "say" },
        { n: "nuts", by: "electricians on a pull", k: "say" },
        { n: "wing nut", by: "electricians, for the winged ones", k: "say" },
        { n: "screw-on connector", by: "the supply counter", k: "sup" }],
    no: "A push-in lever connector, the clear block you drop a straight wire into. Different object, different box." },
  { id: "push-in-lever-connector", n: "Push-in lever connector", t: ["electrical", "low-voltage"],
    o: "A small clear block with a hinged lever per port that clamps a straight stripped wire when closed.",
    a: [{ n: "Wagos", by: "electricians everywhere", k: "tm" },
        { n: "lever nuts", by: "electricians", k: "say" },
        { n: "levers", by: "electricians", k: "say" },
        { n: "lever connector", by: "the supply counter", k: "sup" }],
    no: "A leverless push-in connector, where the wire stabs in and stays and there is no lever to flip back open." },
  { id: "nonmetallic-sheathed-cable", n: "Nonmetallic sheathed cable", t: ["electrical"],
    o: "Insulated conductors and a bare bonding wire lying flat inside a plastic sheath, sold off a roll.",
    a: [{ n: "Romex", by: "American electricians", k: "tm" },
        { n: "Loomex", by: "Canadian electricians", k: "tm" },
        { n: "house wire", by: "residential crews", k: "say" },
        { n: "NM", by: "the supply counter", k: "sup" }],
    no: "Underground feeder cable, the solid grey moulded one with the conductors set into the sheath rather than loose in it." },
  { id: "flexible-metal-conduit", n: "Flexible metal conduit", t: ["electrical"],
    o: "An empty spiral-wound metal tube sold by the coil, with nothing inside it.",
    a: [{ n: "Greenfield", by: "electricians everywhere", k: "tm" },
        { n: "flex", by: "electricians", k: "say" },
        { n: "FMC", by: "the supply counter", k: "sup" }],
    no: "Armored cable, which looks the same on the shelf but comes with the conductors already inside. Men say BX for that." },
  { id: "flexible-nonmetallic-conduit", n: "Flexible nonmetallic conduit", t: ["electrical", "low-voltage"],
    o: "Corrugated plastic tubing sold on a coil, ribbed so it bends by hand and holds the bend.",
    a: [{ n: "smurf tube", by: "electricians and cabling techs, after the blue ones", k: "say" },
        { n: "smurf", by: "the crew", k: "say" },
        { n: "Carlon", by: "electricians", k: "tm" },
        { n: "blue pipe", by: "some crews", k: "say" },
        { n: "ENT", by: "the supply counter", k: "sup" }],
    no: "Rigid nonmetallic conduit, the hard grey glue-together pipe that comes in straight lengths." },
  { id: "conduit-body", n: "Conduit body", t: ["electrical"],
    o: "A small casting threaded into a conduit run with a gasketed cover that lifts off for access.",
    a: [{ n: "Condulet", by: "electricians everywhere", k: "tm" },
        { n: "LB", by: "electricians, by the letter stamped on the casting", k: "say" },
        { n: "body", by: "electricians", k: "say" },
        { n: "access fitting", by: "the supply counter", k: "sup" }],
    no: "A conduit elbow, a plain sweeping bend with no cover and no opening to reach into." },
  { id: "plaster-ring", n: "Plaster ring", t: ["electrical"],
    o: "A stamped steel cover for a box with a raised opening that carries the device out to the finished wall.",
    a: [{ n: "mud ring", by: "electricians", k: "say" },
        { n: "tile ring", by: "some crews", k: "say" },
        { n: "raised cover", by: "the supply counter", k: "sup" },
        { n: "device ring", by: "the supply counter", k: "sup" }],
    no: "A low-voltage mounting bracket, which cabling techs also call a mud ring and which has no box behind it." },
  /* ---- hvac/r -------------------------------------------------------- */
  { id: "air-register", n: "Register", t: ["hvac"],
    o: "Louvered face plate with a damper behind it, fixed over a duct opening.",
    a: [{ n: "vent", by: "everybody outside the trade, and plenty inside it", k: "say" },
        { n: "grille", by: "the field, loosely", k: "say" },
        { n: "register grille", by: "the counter", k: "sup" }],
    no: "A grille, which is the same louvered face with no damper behind it — or a diffuser, which throws the air a different way again. Three fittings, and the field says all three words for all three." },
  { id: "self-drilling-screw", n: "Self-drilling screw", t: ["hvac", "framing", "roofing"],
    o: "Screw with a drill point at the tip that bores its own hole in sheet metal.",
    a: [{ n: "Tek screw", by: "nearly every trade on site", k: "tm" },
        { n: "zip screw", by: "sheet metal crews", k: "say" },
        { n: "hex head", by: "the field", k: "say" },
        { n: "drill point screw", by: "catalogues", k: "sup" }],
    no: "Self-tapping screw — a sharp point with no drill flute; it wants a pilot hole first." },
  { id: "manifold-gauge-set", n: "Manifold gauge set", t: ["hvac"],
    o: "Valved body carrying a high side and a low side gauge, with hose ports on it.",
    a: [{ n: "gauges", by: "the field", k: "say" },
        { n: "the manifold", by: "service techs", k: "say" },
        { n: "charging manifold", by: "the counter", k: "sup" },
        { n: "Yellow Jacket", by: "service techs", k: "tm" },
        { n: "gauge set", by: "the counter", k: "sup" }],
    no: "Plumbing manifold — the ported block that splits water lines out to the fixtures." },
  { id: "micron-gauge", n: "Micron gauge", t: ["hvac"],
    o: "Instrument reading absolute pressure far below atmosphere off a heated sensor element.",
    a: [{ n: "vacuum gauge", by: "the field, loosely", k: "say" },
        { n: "digital vacuum gauge", by: "the counter", k: "sup" },
        { n: "thermistor vacuum gauge", by: "catalogues", k: "sup" },
        { n: "BluVac", by: "service techs", k: "tm" }],
    no: "The compound gauge on a manifold — it reads in inches of mercury, not in microns." },
  { id: "valve-core-removal-tool", n: "Valve core removal tool", t: ["hvac"],
    o: "Ported barrel with a sealed turning shaft and a shutoff, worked with the port closed.",
    a: [{ n: "core tool", by: "the field", k: "say" },
        { n: "core remover", by: "the counter", k: "sup" },
        { n: "CoreMax", by: "service techs", k: "tm" },
        { n: "valve core extractor", by: "catalogues", k: "sup" }],
    no: "Valve core driver — the small keyed stick that turns a core and nothing more." },
  { id: "duct-boot", n: "Duct boot", t: ["hvac"],
    o: "Sheet metal box stepping from a round duct end to a rectangular register opening.",
    a: [{ n: "boot", by: "sheet metal crews", k: "say" },
        { n: "register box", by: "the counter", k: "sup" },
        { n: "boot fitting", by: "catalogues", k: "sup" }],
    no: "Pipe boot — the rubber roof flashing a roofer hands you when you say boot." },
  { id: "foil-tape", n: "Foil tape", t: ["hvac"],
    o: "Aluminum tape with adhesive on the back face, carried on a paper liner.",
    a: [{ n: "duct tape", by: "nearly everyone", k: "say" },
        { n: "aluminum tape", by: "the counter", k: "sup" },
        { n: "metal tape", by: "the field", k: "say" },
        { n: "silver tape", by: "some crews", k: "say" }],
    no: "Cloth duct tape — the woven gray roll with rubber adhesive. Different object, same nickname." },
  /* ---- low-voltage & fire -------------------------------------------- */
  { id: "door-position-switch", n: "Door position switch", t: ["low-voltage"],
    o: "A pair of small bodies, a magnet in the door leaf and a sealed reed contact in the frame facing it.",
    a: [{ n: "door contact", by: "access and alarm techs", k: "say" },
        { n: "mag contact", by: "access and alarm techs", k: "say" },
        { n: "reed", by: "access and alarm techs", k: "say" },
        { n: "DPS", by: "access techs on the radio", k: "say" },
        { n: "recessed contact", by: "the supply counter", k: "sup" }],
    no: "A magnetic lock, which techs also shorten to mag, and which is a plate and armature that holds the door shut." },
  /* ---- gc & site super ----------------------------------------------- */
  { id: "blocking", n: "Blocking", t: ["gc", "framing"],
    o: "Lumber or plywood fastened between the studs or joists, buried behind the finish.",
    a: [{ n: "backing", by: "GCs and supers asking for it", k: "say" },
        { n: "nailer", by: "framers", k: "say" },
        { n: "cats", by: "crews on the west coast", k: "reg" },
        { n: "dwang", by: "crews in Scotland and New Zealand", k: "reg" },
        { n: "noggin", by: "crews in Britain and Ireland", k: "reg" },
        { n: "nogging", by: "UK and Australian crews", k: "reg" }],
    no: "A framing nailer — the gun. That is what shows up when \"nailer\" goes out over the radio." },
  { id: "punch-tape", n: "Low-tack masking tape", t: ["gc"],
    o: "A roll of low-tack crepe masking tape, torn off and stuck on the thing that is wrong.",
    a: [{ n: "blue tape", by: "the whole job", k: "say" },
        { n: "painter's tape", by: "the counter", k: "sup" },
        { n: "low-tack masking tape", by: "the counter", k: "sup" },
        { n: "FrogTape", by: "painters, for any low-tack roll", k: "tm" }],
    no: "Flagging ribbon — the tie-on plastic ribbon off a roll. No adhesive on it at all." },
  { id: "rotary-laser", n: "Rotary laser", t: ["gc", "concrete"],
    o: "A tripod head that spins a level beam right around the room, on its own battery.",
    a: [{ n: "spinner", by: "the field", k: "say" },
        { n: "transit", by: "old hands, for any setup that shoots grade", k: "say" },
        { n: "laser level", by: "the rental counter", k: "sup" },
        { n: "grade laser", by: "the counter", k: "sup" }],
    no: "An optical builder's level (a dumpy) — glass you sight through, and it needs a second man on the rod." },
  { id: "lumber-crayon", n: "Lumber crayon", t: ["gc", "framing"],
    o: "A fat wax-and-pigment stick with no wood casing, that marks wet, dirty and rough surfaces.",
    a: [{ n: "keel", by: "supers, framers and steel hands", k: "say" },
        { n: "timber crayon", by: "crews in Britain and Australia", k: "reg" },
        { n: "marking crayon", by: "the counter", k: "sup" },
        { n: "Markal", by: "layout and steel hands, for any crayon", k: "tm" }],
    no: "A solid paint marker — hard paint in a push-up tube. That is the one that writes on oily steel." },
  { id: "rafter-square", n: "Rafter square", t: ["framing", "roofing", "gc"],
    o: "A triangular square with a lipped fence that hooks the board edge, marked in degrees.",
    a: [{ n: "speed square", by: "nearly every carpenter, whoever made the one in his bag", k: "tm" },
        { n: "quick square", by: "crews raised on the other maker's", k: "tm" },
        { n: "rafter angle square", by: "the tool counter and the catalogue", k: "sup" },
        { n: "triangle square", by: "the counter, when the brand word gets a blank look", k: "sup" }],
    no: "Framing square — the big flat steel L with no fence, for stair and rafter layout." },
  { id: "equipment-pad", n: "Equipment pad", t: ["gc", "concrete"],
    o: "A low slab of concrete poured on top of a finished floor for a machine to sit on.",
    a: [{ n: "housekeeping pad", by: "GCs and mechanical", k: "say" },
        { n: "mech pad", by: "supers on the radio", k: "say" },
        { n: "machine base", by: "some shops", k: "say" },
        { n: "plinth", by: "crews in Britain, India and the Gulf", k: "reg" }],
    no: "A roof curb — the framed and flashed box a rooftop unit sits on. Sheet metal builds that one." },
  { id: "laser-distance-meter", n: "Laser distance meter", t: ["gc"],
    o: "A pocket box that puts a dot on a wall and reads the distance to it.",
    a: [{ n: "Disto", by: "supers, for any make", k: "tm" },
        { n: "laser tape", by: "the field", k: "say" },
        { n: "the gun", by: "supers on the radio", k: "say" },
        { n: "laser measure", by: "the counter", k: "sup" }],
    no: "An infrared thermometer — the other point-and-shoot with a red dot. It reads heat, not length." },
  { id: "moisture-meter", n: "Moisture meter", t: ["gc"],
    o: "A handheld meter, pins or a flat pad, that reads moisture in wood and board.",
    a: [{ n: "pin meter", by: "the field", k: "say" },
        { n: "wood meter", by: "floor layers", k: "say" },
        { n: "damp meter", by: "crews in Britain and Ireland", k: "reg" },
        { n: "Delmhorst", by: "floor layers and restoration hands, for any meter", k: "tm" },
        { n: "Tramex", by: "flooring hands, for any meter", k: "tm" }],
    no: "A slab relative-humidity probe — a sensor sleeved into a hole drilled in the concrete. Different instrument, different question." },
  { id: "curing-compound", n: "Curing compound", t: ["concrete", "gc"],
    o: "A milky liquid sprayed on green concrete that dries to a thin film across the surface.",
    a: [{ n: "cure", by: "the crew", k: "say" },
        { n: "white cure", by: "finishers, for the wax kind", k: "say" },
        { n: "curing membrane", by: "crews in Britain and Australia", k: "reg" },
        { n: "curing agent", by: "the counter", k: "sup" }],
    no: "Cure and seal — same shelf, different drum. That one is meant to stay on the floor as the finish." },
  /* ---- framing & drywall --------------------------------------------- */
  { id: "cutout-router", n: "Drywall cut-out router", t: ["framing"],
    o: "A palm-size router spinning a spiral bit, cutting board freehand off a guide point.",
    a: [{ n: "RotoZip", by: "nearly every hanger, whoever made the tool", k: "tm" },
        { n: "zip tool", by: "hangers on the wall", k: "say" },
        { n: "spiral saw", by: "the counter and the box it comes in", k: "sup" },
        { n: "cut-out tool", by: "the supply-house counter", k: "sup" }],
    no: "A laminate trimmer — the woodworker's palm router, which takes different bits and has no guide point." },
  { id: "gypsum-board", n: "Gypsum board", t: ["framing"],
    o: "Panels of pressed gypsum wrapped in paper, the long edges tapered for tape.",
    a: [{ n: "Sheetrock", by: "most of North America, whoever made the load", k: "tm" },
        { n: "drywall", by: "the field", k: "say" },
        { n: "rock", by: "hangers", k: "say" },
        { n: "wallboard", by: "the supply-house counter", k: "sup" },
        { n: "plasterboard", by: "British, Irish and Australian crews", k: "reg" },
        { n: "Gyprock", by: "Australian crews, whoever made the load", k: "tm" }],
    no: "Cement backer board — the grey gritty panel for tile, which cuts and fastens nothing like board." },
  { id: "setting-compound", n: "Setting-type joint compound", t: ["framing"],
    o: "A powder you mix on site that hardens by chemical set, not by drying.",
    a: [{ n: "hot mud", by: "tapers everywhere", k: "say" },
        { n: "powder mud", by: "the field", k: "say" },
        { n: "bag mud", by: "crews who buy the other one in a bucket", k: "say" },
        { n: "Durabond", by: "tapers, for the hard-setting one", k: "tm" },
        { n: "quick set", by: "some shops", k: "say" },
        { n: "setting compound", by: "the supply-house counter", k: "sup" }],
    no: "Ready-mix joint compound — the bucket of premixed mud that hardens only by drying out." },
  { id: "corner-bead", n: "Corner bead", t: ["framing"],
    o: "Preformed angle trim, metal, vinyl or paper-faced, run down an outside corner.",
    a: [{ n: "bead", by: "tapers", k: "say" },
        { n: "corner", by: "hangers calling for it off the stack", k: "say" },
        { n: "angle bead", by: "British and Irish crews", k: "reg" },
        { n: "beading", by: "UK-trained finishers", k: "reg" },
        { n: "Trim-Tex", by: "finishers, for any vinyl bead", k: "tm" }],
    no: "Casing bead — the L-shaped trim that finishes a board edge against brick, block or a frame." },
  { id: "osb", n: "Oriented strand board", t: ["framing"],
    o: "A panel of wood strands cross-laid and glued, one face printed for grip.",
    a: [{ n: "OSB", by: "the field and the yard", k: "say" },
        { n: "chipboard", by: "homeowners and plenty of crews, though the yard sells that as a furniture panel", k: "say" },
        { n: "waferboard", by: "older Canadian crews", k: "reg" },
        { n: "Aspenite", by: "Ontario and Maritime crews, whoever made it", k: "tm" },
        { n: "Sterling board", by: "British crews, whoever made it", k: "tm" }],
    no: "Particleboard — the fine-chip furniture panel, not a sheathing panel." },
  /* ---- roofing ------------------------------------------------------- */
  { id: "pipe-flashing", n: "Pipe flashing", t: ["roofing"],
    o: "A flanged metal or plastic base with a rubber collar that slips over a vent pipe.",
    a: [{ n: "roof jack", by: "crews in the West", k: "say" },
        { n: "pipe boot", by: "roofers", k: "say" },
        { n: "boot", by: "roofers", k: "say" },
        { n: "vent collar", by: "crews in Britain and Australia", k: "reg" },
        { n: "neoprene boot", by: "the supply counter", k: "sup" }],
    no: "A roof bracket — the steel jack that carries a plank up a steep slope, which plenty of crews also call a roof jack." },
  { id: "roofing-felt", n: "Asphalt-saturated felt", t: ["roofing"],
    o: "A roll of paper mat soaked in asphalt, laid on the deck under shingles.",
    a: [{ n: "tar paper", by: "nearly every crew, though there is no tar in it", k: "say" },
        { n: "felt", by: "the field", k: "say" },
        { n: "roofing paper", by: "homeowners and older crews", k: "say" },
        { n: "underlay", by: "Canadian and British crews", k: "reg" },
        { n: "black paper", by: "some southern crews", k: "say" }],
    no: "Mineral-surfaced cap sheet — the flat-roof sheet, and what a British roofer means when he says roofing felt." },
  { id: "ice-barrier", n: "Self-adhered ice barrier membrane", t: ["roofing"],
    o: "A rubberized asphalt sheet with a sticky back and a peel-off release liner.",
    a: [{ n: "ice and water shield", by: "nearly every crew, whoever made the roll", k: "tm" },
        { n: "ice and water", by: "the field", k: "say" },
        { n: "peel and stick", by: "the field", k: "say" },
        { n: "Blueskin", by: "Canadian crews, whoever made the roll", k: "tm" },
        { n: "eave protection", by: "Canadian crews and counters", k: "reg" }],
    no: "Asphalt-saturated felt — the plain nailed-down paper, with no adhesive on the back." },
  { id: "step-flashing", n: "Step flashing", t: ["roofing"],
    o: "Bent metal squares, one laid into each shingle course where a roof runs into a wall.",
    a: [{ n: "steps", by: "roofers working a sidewall", k: "say" },
        { n: "step tins", by: "some Northeast crews", k: "say" },
        { n: "soakers", by: "British and Irish roofers on slate and tile", k: "reg" },
        { n: "shingle flashing", by: "the supply-house counter", k: "sup" }],
    no: "Counter flashing — the piece let into the wall above that laps down over the steps." },
  { id: "laminated-shingle", n: "Laminated asphalt shingle", t: ["roofing"],
    o: "An asphalt shingle built up from bonded mats, so the tabs sit thick and shadowed.",
    a: [{ n: "architectural", by: "nearly every crew and every homeowner", k: "say" },
        { n: "arch shingles", by: "crews on the roof", k: "say" },
        { n: "laminates", by: "crews and estimators", k: "say" },
        { n: "dimensional", by: "the supply-house counter and the catalogue", k: "sup" },
        { n: "Timberline", by: "crews who order a whole roof by that word, whoever made it", k: "tm" }],
    no: "Strip shingle — the flat shingle with cut tabs and no laminate on it, a different roof." },
  { id: "roof-cement", n: "Asphalt roofing cement", t: ["roofing"],
    o: "A trowel-grade paste of asphalt and fiber, sold in tubs and in tubes.",
    a: [{ n: "mastic", by: "low-slope crews", k: "say" },
        { n: "tar", by: "the field and every homeowner", k: "say" },
        { n: "plastic cement", by: "the roofing counter and the label on the tub", k: "sup" },
        { n: "flashing cement", by: "the counter, for the stiffer tub", k: "sup" },
        { n: "Henry's", by: "crews raised on that tub, whoever made it", k: "tm" },
        { n: "Black Jack", by: "crews buying it off the big-box shelf", k: "tm" }],
    no: "Plastic cement in the masonry aisle — a bagged stucco and mortar cement, a different material entirely." },
  { id: "mod-bit", n: "Modified bitumen membrane", t: ["roofing"],
    o: "An asphalt roll sheet carrying polymer and a fabric mat, torched or mopped down.",
    a: [{ n: "mod bit", by: "low-slope crews", k: "say" },
        { n: "torch-down", by: "US crews", k: "say" },
        { n: "torch-on", by: "Canadian and British crews", k: "reg" },
        { n: "SBS", by: "crews naming it off the rubber in it", k: "say" },
        { n: "modified", by: "the supply-house counter", k: "sup" }],
    no: "Single-ply membrane — a sheet whose laps are welded with hot air; mod bit burns down under a torch flame and is never welded." },
  { id: "epdm", n: "EPDM membrane", t: ["roofing"],
    o: "A black synthetic-rubber sheet in wide rolls, seamed with tape or with glue.",
    a: [{ n: "rubber", by: "low-slope crews", k: "say" },
        { n: "rubber roof", by: "the field and the building owner", k: "say" },
        { n: "Carlisle", by: "crews naming it off the roll they were raised on", k: "tm" },
        { n: "Firestone", by: "older crews and older spec sheets", k: "tm" },
        { n: "ethylene propylene diene monomer", by: "the spec sheet and the counter", k: "sup" }],
    no: "TPO membrane — the white sheet whose laps are welded with hot air; rubber will not weld to it." },
  { id: "tpo", n: "Thermoplastic polyolefin membrane", t: ["roofing"],
    o: "A white plastic sheet with scrim inside, laps melted together with hot air.",
    a: [{ n: "TPO", by: "everybody on a low-slope roof", k: "say" },
        { n: "white roof", by: "crews and building owners", k: "say" },
        { n: "Sure-Weld", by: "crews naming it off the roll, whoever made it", k: "tm" },
        { n: "EverGuard", by: "crews naming it off the roll, whoever made it", k: "tm" },
        { n: "thermoplastic", by: "the spec and the supply-house counter", k: "sup" }],
    no: "PVC membrane — also white, also welded, and a different sheet that will not weld to this one." },
  { id: "hand-welder", n: "Hot-air hand welder", t: ["roofing"],
    o: "A hand tool blowing temperature-set hot air through a nozzle to melt sheet laps.",
    a: [{ n: "Leister", by: "single-ply crews, whoever made the gun", k: "tm" },
        { n: "Triac", by: "crews naming it off the one that lives on the roof", k: "tm" },
        { n: "welder", by: "the crew, once they are up on the deck", k: "say" },
        { n: "hot-air gun", by: "the supply-house counter", k: "sup" }],
    no: "A roofing torch — the open-flame tool that burns mod bit down, which never touches single-ply." },
  /* ---- creative / video ---------------------------------------------- */
  { id: "nd-filters", n: "ND filters", t: ["creative"],
    o: "Neutral grey glass or resin, square or screw-in, that darkens the image without tinting it.",
    a: [{ n: "NDs", by: "camera crews", k: "say" },
        { n: "neutral density", by: "the rental counter", k: "sup" }],
    no: "Neutral density window gel — the sheet stock taped over glass, not a lens filter." },
  { id: "grip-head", n: "Grip head", t: ["creative"],
    o: "A cast knuckle with grooved jaws and a turning handle, clamping a rod or frame to a stand.",
    a: [{ n: "gobo head", by: "grips and gaffers", k: "say" },
        { n: "knuckle", by: "grips", k: "say" },
        { n: "C-stand head", by: "the rental counter", k: "sup" }],
    no: "A gobo in a lighting fixture — the cut metal pattern that throws a shape. Same word, different object." },
  { id: "clapperboard", n: "Clapperboard", t: ["creative"],
    o: "A slate board with a hinged striped arm that claps shut against it.",
    a: [{ n: "slate", by: "camera and sound crews", k: "say" },
        { n: "sticks", by: "camera assistants and sound mixers", k: "say" },
        { n: "clapper", by: "most crews", k: "say" }],
    no: "A tripod — camera crews call those sticks as well, and that is what turns up." },
  /* ---- concrete & rebar ---------------------------------------------- */
  { id: "concrete-rake", n: "Concrete rake", t: ["concrete"],
    o: "A wide flat blade with a hooked lip on a long handle, pulled through fresh mud.",
    a: [{ n: "come-along", by: "placers everywhere", k: "say" },
        { n: "mud rake", by: "some crews", k: "say" },
        { n: "placer", by: "the counter", k: "sup" },
        { n: "concrete placer rake", by: "the counter", k: "sup" }],
    no: "A ratchet cable puller — that is the come-along a rigger or a driver brings, and it moves no mud." },
  { id: "internal-vibrator", n: "Concrete vibrator", t: ["concrete"],
    o: "A motor driving a flexible shaft with a steel head on the end, dunked into the pour.",
    a: [{ n: "stinger", by: "placers and supers", k: "say" },
        { n: "the stick", by: "the crew", k: "say" },
        { n: "poker", by: "crews in Britain, Ireland and Australia", k: "reg" },
        { n: "immersion vibrator", by: "the rental counter", k: "sup" }],
    no: "An extension cord — and a welder's electrode holder. Both are called a stinger too. Say which one you want." },
  { id: "bull-float", n: "Bull float", t: ["concrete"],
    o: "A wide flat blade on a swivel bracket, pushed and pulled across fresh concrete.",
    a: [{ n: "bull", by: "the crew", k: "say" },
        { n: "swivel float", by: "the counter", k: "sup" },
        { n: "channel float", by: "some counters", k: "sup" }],
    no: "A fresno — a steel trowel blade on the same handles. Steel, not magnesium, and it is not interchangeable." },
  { id: "power-trowel", n: "Power trowel", t: ["concrete"],
    o: "A walk-behind machine with spinning steel blades under a guard ring, driven across the slab.",
    a: [{ n: "power float", by: "crews in Britain and Ireland", k: "reg" },
        { n: "helicopter", by: "crews in Britain and Australia", k: "reg" },
        { n: "whirlybird", by: "some crews — and it is the roof turbine to a roofer", k: "say" },
        { n: "trowel machine", by: "the rental counter", k: "sup" }],
    no: "A ride-on trowel — the seated machine with its own steering. Rental stocks both under the same word." },
  { id: "screed-bar", n: "Screed straightedge", t: ["concrete"],
    o: "A straight magnesium or aluminum bar with no motor on it, dragged across the forms.",
    a: [{ n: "screed", by: "the crew", k: "say" },
        { n: "straightedge", by: "the crew", k: "say" },
        { n: "strike-off bar", by: "some crews", k: "say" },
        { n: "screed bar", by: "the counter", k: "sup" }],
    no: "A power screed — the vibrating or roller machine that rides the forms. Rental hears \"screed\" and sends that." },
  { id: "bar-support", n: "Bar support", t: ["concrete"],
    o: "The plastic, wire or precast concrete piece that holds reinforcing steel up off the base.",
    a: [{ n: "chair", by: "rodbusters everywhere", k: "say" },
        { n: "dobie", by: "crews out west, for the precast block with the wire in it", k: "say" },
        { n: "sand plate", by: "slab crews, for the plate-footed kind", k: "say" },
        { n: "bolster", by: "the counter", k: "sup" },
        { n: "spacer", by: "crews in Britain and Australia", k: "reg" }],
    no: "A dowel basket — the welded frame that carries smooth dowels across a joint. Steel too, different job." },
  { id: "rebar-twister", n: "Rebar tie tool", t: ["concrete"],
    o: "A hooked steel spindle in a handle that spins a wire tie tight when you pull it.",
    a: [{ n: "twister", by: "rodbusters", k: "say" },
        { n: "tie hook", by: "the crew", k: "say" },
        { n: "wire twister", by: "the counter", k: "sup" },
        { n: "bar tie tool", by: "the counter", k: "sup" }],
    no: "A battery tie gun — the powered tool that wraps and twists in one squeeze. Same job, different order." },
  { id: "welded-wire-mesh", n: "Welded wire mesh", t: ["concrete"],
    o: "A grid of steel wires welded at every crossing, delivered in flat sheets or a roll.",
    a: [{ n: "mesh", by: "the crew", k: "say" },
        { n: "remesh", by: "the counter", k: "sup" },
        { n: "wire fabric", by: "the counter and the prints", k: "sup" },
        { n: "reo mesh", by: "crews in Australia and New Zealand", k: "reg" }],
    no: "Fibers dosed into the mix — plenty of crews call that \"fiber mesh\", and it arrives in the truck, not on a pallet." },
  { id: "form-release", n: "Form release agent", t: ["concrete"],
    o: "The oil or water-based emulsion wiped or sprayed onto form faces before the pour.",
    a: [{ n: "form oil", by: "form setters everywhere", k: "say" },
        { n: "release", by: "the crew", k: "say" },
        { n: "shuttering oil", by: "crews in Britain, Ireland and the Gulf", k: "reg" },
        { n: "mould oil", by: "precast shops overseas", k: "say" }],
    no: "Bond breaker for tilt-up — sprayed on the casting slab so the panel lifts off. Different drum, different job." },
];
