/**
 * VECTOR HYBRID EXPORT
 * Section 15.2: SVG/PDF Export with embedded images
 *
 * Exports layout as vector paths with high-res bitmaps embedded.
 * Use case: Laser cutter frames, print production, Cricut/Silhouette.
 */

import { LayoutItem } from '../../lib/layout';
import { ImageAsset } from '../../types';

interface VectorExportOptions {
  width: number;
  height: number;
  unit: 'px' | 'mm' | 'in';
  dpi: number;
  embedImages: boolean;
  cutLineColor: string;
  cutLineWidth: number;
}

const DEFAULT_OPTIONS: VectorExportOptions = {
  width: 300,
  height: 200,
  unit: 'mm',
  dpi: 300,
  embedImages: true,
  cutLineColor: '#FF0000', // Red for laser cutter
  cutLineWidth: 0.1 // Hairline
};

/**
 * Convert layout path to SVG path data
 */
const pathToSVGData = (path: { x: number; y: number }[]): string => {
  return path.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x.toFixed(3)} ${p.y.toFixed(3)}`).join(' ') + ' Z';
};

/**
 * Export to SVG with cut lines and optional image embedding
 */
export const exportToSVG = async (
  layoutItems: LayoutItem[],
  images: ImageAsset[],
  options: Partial<VectorExportOptions> = {}
): Promise<string> => {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const { width, height, unit, cutLineColor, cutLineWidth, embedImages } = opts;

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 ${width} ${height}"
     width="${width}${unit}"
     height="${height}${unit}">
  <title>Smart Crop Collage Export</title>
  <desc>Generated by Smart Crop Collage Maker</desc>

  <!-- LAYERS: Images (print) / Cut Lines (cut) -->
  <g id="images-layer">`;

  // Embed images if requested
  if (embedImages && images.length > 0) {
    for (let i = 0; i < layoutItems.length; i++) {
      const item = layoutItems[i];
      const imgData = images[i % images.length];
      if (!imgData) continue;

      const clipId = `clip-${i}`;
      const pathData = pathToSVGData(item.path);

      svg += `
    <defs>
      <clipPath id="${clipId}">
        <path d="${pathData}"/>
      </clipPath>
    </defs>
    <image
      clip-path="url(#${clipId})"
      x="${item.bounds.x}" y="${item.bounds.y}"
      width="${item.bounds.w}" height="${item.bounds.h}"
      xlink:href="${imgData.src}"
      preserveAspectRatio="xMidYMid slice"/>`;
    }
  }

  svg += `
  </g>

  <!-- CUT LINES - For laser cutter / die cut -->
  <g id="cut-lines-layer" fill="none" stroke="${cutLineColor}" stroke-width="${cutLineWidth}" vector-effect="non-scaling-stroke">`;

  for (const item of layoutItems) {
    const pathData = pathToSVGData(item.path);
    svg += `
    <path d="${pathData}"/>`;
  }

  // Outer frame cut line
  svg += `
    <rect x="0" y="0" width="${width}" height="${height}" id="outer-frame"/>`;

  svg += `
  </g>
</svg>`;

  return svg;
};

/**
 * Export to PDF using jsPDF (must be loaded externally)
 * Returns base64 PDF data URI
 */
export const exportToPDF = async (
  canvas: HTMLCanvasElement,
  layoutItems: LayoutItem[],
  options: Partial<VectorExportOptions> = {}
): Promise<string> => {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  // Check if jsPDF is available
  // @ts-ignore
  if (typeof window.jspdf === 'undefined') {
    throw new Error('jsPDF not loaded. Add: <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>');
  }

  // @ts-ignore
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF({
    orientation: opts.width > opts.height ? 'landscape' : 'portrait',
    unit: opts.unit,
    format: [opts.width, opts.height]
  });

  // Add raster image as background
  const imgData = canvas.toDataURL('image/jpeg', 0.95);
  pdf.addImage(imgData, 'JPEG', 0, 0, opts.width, opts.height);

  // Add vector cut lines on top
  pdf.setDrawColor(255, 0, 0); // Red
  pdf.setLineWidth(opts.cutLineWidth);

  for (const item of layoutItems) {
    const path = item.path;
    if (path.length < 2) continue;

    // Scale path coordinates to PDF units
    const scaleX = opts.width / canvas.width;
    const scaleY = opts.height / canvas.height;

    pdf.moveTo(path[0].x * scaleX, path[0].y * scaleY);
    for (let i = 1; i < path.length; i++) {
      pdf.lineTo(path[i].x * scaleX, path[i].y * scaleY);
    }
    pdf.lineTo(path[0].x * scaleX, path[0].y * scaleY); // Close path
    pdf.stroke();
  }

  // Outer frame
  pdf.rect(0, 0, opts.width, opts.height, 'S');

  return pdf.output('datauristring');
};

/**
 * Export cut lines only (for Cricut/Silhouette)
 */
export const exportCutLinesOnly = (
  layoutItems: LayoutItem[],
  options: Partial<VectorExportOptions> = {}
): string => {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const { width, height, unit, cutLineColor, cutLineWidth } = opts;

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 ${width} ${height}"
     width="${width}${unit}"
     height="${height}${unit}">
  <title>Collage Cut Lines</title>
  <g fill="none" stroke="${cutLineColor}" stroke-width="${cutLineWidth}">`;

  for (const item of layoutItems) {
    const pathData = pathToSVGData(item.path);
    svg += `
    <path d="${pathData}"/>`;
  }

  svg += `
    <rect x="0" y="0" width="${width}" height="${height}"/>
  </g>
</svg>`;

  return svg;
};

/**
 * Download helper
 */
export const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};
