/* FIELD TOOLKIT — SHARED: THE POOLED DOCUMENT VOCABULARY.
 * Aldrin Payopay <aldrin.gdf@gmail.com> — GPL-3.0
 *
 * GENERATED — do not hand-edit. Regenerate with:
 *     node tools/toolkit-gates/build-docsindex.mjs
 * That file carries the measurement, the rails and the panel's reasoning; the
 * deploy runs it with --check against the staged artifact and refuses a diff, so
 * this cannot quietly stop being true.
 *
 * Eight documents live on all thirteen trades and every trade renamed them —
 * delay-notice alone goes by seven names. Each row below is one document id and
 * every name or `aka` ANY trade wrote for it. shared/docspec.js adds these to
 * the search index of a trade that ALREADY CARRIES that document id, so a man
 * searching his own shelf gets thirteen authors' words for it instead of one.
 *
 * It can never introduce a document: a term is only pooled onto trades that
 * already hold its document, single-trade documents are excluded outright, a
 * term meaning two different documents anywhere on the rack is excluded, and so
 * is any term within one edit of a term meaning a different document.
 *
 * 19 trades · 13 poolable document ids · 440 terms
 * · 41 ambiguous term(s) refused · 14 quarantined as near-names
 */
window.DOCS_POOL = {
  "change-request": ["backup letter", "change order", "change order narrative", "change order request", "change order write up", "co", "COR", "COR write-up", "entitlement letter", "extra", "extra work", "Extra Work / Change Write-Up", "Extra Work Write-Up", "not in our number", "not on my prints", "not on the drawings", "out of scope", "out of scope letter", "PCO", "PCO justification", "scope change", "t and m narrative", "T&M cover", "T&M cover letter", "the extra", "The Extra Work Write-Up", "This Wasn't In The Dirt We Bid", "why it's extra", "Why It's Extra (the reason above the pricing)", "Why It's Extra — The Reason, Not the Number"],
  "daily-report": ["bolt up", "bolted up", "crane time", "daily", "Daily Field Report", "daily log", "daily narrative", "daily report", "daily update", "day report", "decking", "dfr", "end of day", "end of day report", "eod", "erection daily", "field report", "foreman daily", "foreman's daily", "how the day went", "made up", "pieces set", "production report", "set today", "shift report", "super's log", "superintendent's daily", "The Daily", "The Daily (what we closed, what stopped us)", "The Daily (what we put in, what stopped us)", "The Day Report", "The Day Report (Shoot Day or Edit Day)", "welded out", "what we did today", "what we got done today", "what we set", "work performed today", "wrap report"],
  "damage-found": ["already cracked", "already damaged", "already like that", "back charge", "backcharge", "before I touched it", "before we started", "bent in the yard", "came in like this", "coating holiday", "condition", "condition of existing", "cracked before we got there", "damage", "Damage Notice", "Damage / Pre-Existing Condition Note", "damaged beam", "damaged leaf", "damaged our work", "dented frame", "door damaged after hanging", "existing condition", "Existing Conditions Letter (this was here before us)", "existing damage", "existing pipe condition", "found condition letter", "found damage", "found it this way", "How It Was When We Got There", "How the Slab Was When I Got There", "It Was Like That Before We Started", "It Was Like That When I Got Here — The Unit Before I Touched It", "It Was Like That When We Got There", "location condition", "My Doors, After Somebody Else Got To Them", "photo walk before we start", "pre-existing", "pre-existing damage", "previous contractor", "prior condition", "prior damage", "protection of work", "rework notice", "scratched door", "somebody else's work", "the walk before the first piece comes off", "they burned my steel", "they cut my beam", "they cut my pipe", "they wrecked my work", "we damaged theirs", "we're not adopting this", "welded to my steel", "What Was Already Like That When We Got Here"],
  "damage-reply": ["chipped it", "crack", "cracked wall", "cut and patch response", "damage reply", "damage response", "efflorescence", "It Wasn't Us (a punch item for damage somebody else opened)", "not our crack", "not our work", "Not Our Work — Damage and Crack Reply", "punch list reply", "somebody drove on it", "spall", "staining", "The Crack That Isn't Ours", "they say it's ours", "they say we broke it", "who opened this"],
  "delay-notice": ["can't proceed", "cant start", "date is moving", "delay letter", "delay notice", "Delay / We're Held Up Notice", "held up", "impact", "impact letter", "no answer", "not released", "notice", "notice letter", "notice of delay", "notice of impact", "Notice of Impact (we're being held up)", "papering it", "schedule impact", "stacked trades", "stacking of trades", "The Day We Couldn't Fly", "The Impact Notice", "the wall is open and we're waiting", "time impact", "Waiting On Somebody", "waiting on the GC", "waiting on the roofer", "waiting on the windows", "we can't get in there", "We Got Held", "We're Held Up", "We're Rolling Nothing", "We're Standing", "We're Waiting On Somebody"],
  "handover": ["area turnover", "bac-t cover letter", "beneficial occupancy", "chlorination letter", "control key", "cores", "delivered", "delivery", "Delivery Note — What I'm Sending", "done", "final", "final acceptance", "final bolt-up", "final files", "final walk on the siding", "flush and disinfect", "frame complete", "handed it over running", "handed the house back", "Handing It Back", "here it is", "keying", "keys", "Keys, Cores and the Openings I'm Turning Over", "leftover material", "maintenance period", "O and M turnover", "owner training", "permanent cores", "punch", "punch list", "put in service", "sending it over", "substantial completion", "The Day It Becomes Theirs", "the painter's joints", "The Turnover", "The Turnover Write-Up", "Topped Out — Turning the Frame Over", "topping out", "touch up", "touch-up paint", "turned it over", "Turned Over Running — The Day It Becomes Theirs", "Turning the Lot Over For Good", "Turnover / Closeout", "Turnover / Handover Summary", "turnover letter", "Turnover Letter (system put in service)", "warranty paperwork", "warranty registration", "we put it in service", "What I Left The Grade At"],
  "incident-report": ["a load came down", "accident", "accident report", "accident write up", "arc flash", "caught between", "dropped a load", "dropped load", "fell", "first aid", "first report", "flash burn", "gear damage", "hit by the load", "incident", "Incident / Near-Miss Report", "Incident Statement", "injury", "injury report", "my statement", "near miss", "on set", "property damage", "recordable", "safety report", "safety writeup", "shock", "somebody got hurt", "Something Happened (Incident / Near-Miss)", "struck by", "The Incident Write-Up", "witness statement"],
  "look-ahead": ["before I can plant", "closure notice", "erection sequence", "lift plan", "look ahead", "Look-Ahead / What Has To Be Ready", "Look-Ahead / What We Need", "lookahead", "next lift", "next week", "nursery lead time", "plan", "plant order", "raising sequence", "sequence", "status", "this week", "three week", "two week", "update", "what has to be in before we fly", "What Has To Be True Before I Can Plant", "What Has To Be True Before The Machine Moves", "What Has To Line Up Before We Pave", "what I need", "what's ready to set", "whats coming", "where are we", "Where Everything Stands"],
  "meeting-minutes": ["call notes", "coordination", "coordination meeting", "Coordination Meeting Notes", "meeting", "minutes", "Notes From the Call", "oac", "OAC / Coordination Notes", "oac minutes", "progress meeting", "review call", "sub meeting", "we agreed on the call", "weekly notes"],
  "not-in-my-number": ["added openings extra cost", "assumptions", "cor narrative doors and frames", "door hardware change order narrative", "exclusions", "extra work doors not in contract", "field change doors extra", "my bid excludes", "not in my price", "not in my scope", "out of scope frame work", "proposal clarifications", "qualifications", "rework not in my scope doors", "scope not in my bid doors", "t and m ticket door install", "That Wasn't In My Number", "What My Number Doesn't Cover", "who is paying for these doors"],
  "service-writeup": ["11-month walk item", "a piece blew off", "adjustment", "bollard hit", "buckled panel", "call write-up", "Callback on an Opening", "came back", "came back out", "came loose", "closer", "closing notes", "come back", "customer letter", "dead plants call", "door dragging", "door won't close", "field service report", "first trip", "found did recommend", "fsr", "gap opened up", "gate dropped", "handrail loose", "hardware adjustment", "hollow spot", "iced up", "invoice write-up", "irrigation repair", "job story", "latch not catching", "lifted seam", "Misc-Metals Come-Back — What I Found When I Went Back", "no cool", "no cooling", "no heat", "PM report", "post-turnover call", "rail came loose", "recharge", "repair", "replacement", "service", "service call", "Service Call Write-Up", "Service Call Write-Up (the ticket narrative)", "Service Call Write-Up — What I Found, What I Did", "service report", "service ticket", "service ticket narrative", "service ticket write-up", "Service Write-Up", "site visit notes", "site visit report", "stair moved", "tech notes", "The Callback (Settlement, Washout, A Lid That Sank)", "The Callback — What I Found When I Went Back", "the joint opened up", "the narrative box", "The Warranty Call — What I Found At The Plant", "The Write-Up (found, did, still wrong)", "ticket write up", "topped it off", "trouble call", "trouble ticket narrative", "troubleshooting report", "warranty", "warranty call", "Warranty / Callback Write-Up", "warranty response", "warranty vs damage", "water showing inside after a re-side", "went back", "what I did", "what I did on the call", "won't latch", "work order narrative", "work performed"],
  "site-walk": ["access for the crane", "as-found", "crane access", "crane pad", "field measure", "field verification", "laydown", "laydown area", "location scout", "Location Scout Write-Up", "overhead line", "pre-bid walk", "pre-erection walk", "pre-install walk", "recce", "scout", "shake out", "shakeout", "shakeout walk", "site survey", "site visit", "site walk", "Site Walk / As-Found Write-Up", "Site Walk / Survey Write-Up", "survey", "tech scout", "The Walk Before We Move In", "walk", "walkthrough", "went and looked", "where the crane sits"],
  "toolbox-talk": ["jha", "pre task", "safety meeting", "tailgate", "tool box talk", "toolbox", "Toolbox Talk / Tailgate Note"]
};
