/* FIELD TOOLKIT — SHARED: THE POOLED DOCUMENT VOCABULARY.
 * Aldrin Payopay <aldrin.gdf@gmail.com> — GPL-3.0
 *
 * GENERATED — do not hand-edit. Regenerate with:
 *     node tools/toolkit-gates/build-docsindex.mjs
 * That file carries the measurement, the rails and the panel's reasoning; the
 * deploy runs it with --check against the staged artifact and refuses a diff, so
 * this cannot quietly stop being true.
 *
 * Eight documents live on all thirteen trades and every trade renamed them —
 * delay-notice alone goes by seven names. Each row below is one document id and
 * every name or `aka` ANY trade wrote for it. shared/docspec.js adds these to
 * the search index of a trade that ALREADY CARRIES that document id, so a man
 * searching his own shelf gets thirteen authors' words for it instead of one.
 *
 * It can never introduce a document: a term is only pooled onto trades that
 * already hold its document, single-trade documents are excluded outright, a
 * term meaning two different documents anywhere on the rack is excluded, and so
 * is any term within one edit of a term meaning a different document.
 *
 * 17 trades · 13 poolable document ids · 340 terms
 * · 37 ambiguous term(s) refused · 10 quarantined as near-names
 */
window.DOCS_POOL = {
  "change-request": ["backup letter", "change order", "change order narrative", "change order request", "change order write-up", "co", "COR", "COR write-up", "entitlement letter", "extra", "extra work", "Extra Work / Change Write-Up", "Extra Work Write-Up", "not in our number", "not on my prints", "out of scope", "out of scope letter", "PCO", "PCO justification", "scope change", "t and m narrative", "T&M cover", "T&M cover letter", "the extra", "The Extra Work Write-Up", "This Wasn't In The Dirt We Bid", "Why It's Extra (the reason above the pricing)"],
  "daily-report": ["daily", "Daily Field Report", "daily log", "daily narrative", "daily report", "daily update", "day report", "dfr", "end of day", "end of day report", "eod", "field report", "foreman daily", "foreman's daily", "how the day went", "production report", "shift report", "super's log", "superintendent's daily", "The Daily", "The Daily (what we closed, what stopped us)", "The Daily (what we put in, what stopped us)", "The Day Report", "The Day Report (Shoot Day or Edit Day)", "what we did today", "what we got done today", "work performed today", "wrap report"],
  "damage-found": ["already cracked", "already damaged", "back charge", "backcharge", "before we started", "came in like this", "condition", "condition of existing", "damage", "Damage Notice", "Damage / Pre-Existing Condition Note", "damaged leaf", "damaged our work", "dented frame", "door damaged after hanging", "Existing Conditions Letter (this was here before us)", "existing pipe condition", "found condition letter", "found damage", "How It Was When We Got There", "How the Slab Was When I Got There", "interference", "It Was Like That When We Got There", "location condition", "My Doors, After Somebody Else Got To Them", "pre-existing", "pre-existing damage", "prior condition", "prior damage", "protection of work", "rework notice", "scratched door", "they cut my pipe", "they wrecked my work", "we damaged theirs", "we're not adopting this", "What Was Already Like That When We Got Here"],
  "damage-reply": ["chipped it", "crack", "cracked wall", "cut and patch response", "damage reply", "damage response", "efflorescence", "It Wasn't Us (a punch item for damage somebody else opened)", "not our crack", "not our work", "Not Our Work — Damage and Crack Reply", "punch list reply", "somebody cut my wall", "somebody drove on it", "spall", "staining", "The Crack That Isn't Ours", "they say it's ours", "they say we broke it", "who opened this"],
  "delay-notice": ["can't proceed", "cant start", "date is moving", "delay letter", "delay notice", "Delay / We're Held Up Notice", "held up", "impact", "impact letter", "no answer", "not released", "notice", "notice letter", "notice of delay", "notice of impact", "Notice of Impact (we're being held up)", "papering it", "schedule impact", "stacked trades", "stacking of trades", "The Impact Notice", "time impact", "we can't get in there", "We Got Held", "We're Held Up", "We're Rolling Nothing", "We're Standing", "We're Waiting On Somebody"],
  "handover": ["area turnover", "bac-t cover letter", "beneficial occupancy", "chlorination letter", "control key", "cores", "delivered", "delivery", "Delivery Note — What I'm Sending", "done", "final", "final acceptance", "final files", "flush and disinfect", "here it is", "keying", "keys", "Keys, Cores and the Openings I'm Turning Over", "maintenance period", "permanent cores", "put in service", "sending it over", "substantial completion", "The Day It Becomes Theirs", "The Turnover", "The Turnover Write-Up", "Turning the Lot Over For Good", "Turnover / Closeout", "Turnover / Handover Summary", "turnover letter", "Turnover Letter (system put in service)", "we put it in service", "What I Left The Grade At"],
  "incident-report": ["accident", "accident report", "accident write up", "arc flash", "first aid", "first report", "gear damage", "incident", "Incident / Near-Miss Report", "Incident Statement", "injury", "injury report", "my statement", "near miss", "on set", "property damage", "recordable", "safety report", "safety writeup", "shock", "somebody got hurt", "Something Happened (Incident / Near-Miss)", "The Incident Write-Up", "witness statement"],
  "look-ahead": ["before I can plant", "closure notice", "look ahead", "Look-Ahead / What Has To Be Ready", "Look-Ahead / What We Need", "lookahead", "next week", "nursery lead time", "plan", "plant order", "status", "this week", "three week", "two week", "update", "What Has To Be True Before I Can Plant", "What Has To Be True Before The Machine Moves", "What Has To Line Up Before We Pave", "what I need", "whats coming", "where are we", "Where Everything Stands"],
  "meeting-minutes": ["call notes", "coordination", "coordination meeting", "Coordination Meeting Notes", "meeting", "minutes", "Notes From the Call", "oac", "OAC / Coordination Notes", "oac minutes", "progress meeting", "review call", "sub meeting", "we agreed on the call", "weekly notes"],
  "not-in-my-number": ["added openings extra cost", "assumptions", "cor narrative doors and frames", "door hardware change order narrative", "exclusions", "extra work doors not in contract", "field change doors extra", "my bid excludes", "not in my price", "not in my scope", "out of scope frame work", "proposal clarifications", "qualifications", "rework not in my scope doors", "scope not in my bid doors", "t and m ticket door install", "That Wasn't In My Number", "What My Number Doesn't Cover", "who is paying for these doors"],
  "service-writeup": ["11-month walk item", "adjustment", "call", "call write-up", "Callback on an Opening", "came back out", "closer", "closing notes", "come back", "customer letter", "dead plants call", "door dragging", "door won't close", "field service report", "found did recommend", "fsr", "gap opened up", "hardware adjustment", "hollow spot", "invoice write-up", "irrigation repair", "job story", "latch not catching", "lifted seam", "PM report", "post-turnover call", "repair", "replacement", "service", "service call", "Service Call Write-Up", "Service Call Write-Up (the ticket narrative)", "Service Call Write-Up — What I Found, What I Did", "service report", "service ticket", "service ticket narrative", "service ticket write-up", "Service Write-Up", "site visit notes", "site visit report", "tech notes", "The Callback (Settlement, Washout, A Lid That Sank)", "the narrative box", "The Warranty Call — What I Found At The Plant", "The Write-Up (found, did, still wrong)", "ticket write up", "trouble call", "trouble ticket narrative", "troubleshooting report", "warranty", "warranty call", "Warranty / Callback Write-Up", "warranty response", "warranty vs damage", "went back", "what I did", "what I did on the call", "won't latch", "work order narrative", "work performed"],
  "site-walk": ["as-found", "field measure", "field verification", "location scout", "Location Scout Write-Up", "pre-bid walk", "pre-install walk", "recce", "scout", "site survey", "site visit", "site walk", "Site Walk / As-Found Write-Up", "Site Walk / Survey Write-Up", "survey", "tech scout", "The Walk Before We Move In", "walk", "walkthrough", "went and looked"],
  "toolbox-talk": ["jha", "pre task", "safety meeting", "tailgate", "tool box talk", "toolbox", "Toolbox Talk / Tailgate Note"]
};
