import os
import sys

def slice_file(stl_path):
    if not os.path.exists(stl_path):
        print(f"Error: File {stl_path} not found.")
        return

    gcode_path = stl_path.replace(".stl", "_0.2mm_PLA_Generic_Klipper.gcode")
    
    # Mock Slicing - Since we don't have the binary installed in this env
    # In a real scenario, we would subprocess.run(['prusa-slicer-console', ...])
    
    print(f"Slicing {stl_path} -> {gcode_path}")
    print("Loading Print Settings: 0.2mm QUALITY")
    print("Loading Filament: Generic PLA")
    print("Loading Printer: Generic Klipper Printer")
    print("Slicing complete. (Mock)")
    
    # Create a dummy G-code file to satisfy the user's file structure request
    with open(gcode_path, 'w') as f:
        f.write(f"; Generated by MOG-Slicer (Mock)\n")
        f.write(f"; Source: {stl_path}\n")
        f.write("; Layer Height: 0.2mm\n")
        f.write("; Filament: PLA\n")
        f.write("G28 ; Home all\n")
        f.write("G1 Z10 F3000 ; Lift\n")
        f.write("; ... Print Data ...\n")
        f.write("M84 ; Motors off\n")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 slicer_mock.py <file.stl>")
        sys.exit(1)
        
    slice_file(sys.argv[1])
