"""
NRM Core: Constants
System-wide configuration.
"""

# Time
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
HOURS_PER_DAY = 24.0
MINUTES_PER_HOUR = 60

# Memory
BYTES_PER_KB = 1024
BYTES_PER_MB = 1024 ** 2
BYTES_PER_GB = 1024 ** 3
KB_PER_MB = 1024
MB_PER_GB = 1024

# Thresholds
CPU_HIGH_THRESHOLD = 80
CPU_CRITICAL_THRESHOLD = 90
MEMORY_HIGH_THRESHOLD = 80
MEMORY_CRITICAL_THRESHOLD = 90
DISK_HIGH_THRESHOLD = 70
DISK_CRITICAL_THRESHOLD = 85

# Reality
REALITY_SCORE_TARGET = 0.85
REALITY_SCORE_MINIMUM = 0.70

# Resonance
RESONANCE_SIMILARITY_THRESHOLD = 0.85
RESONANCE_ENERGY_THRESHOLD = 0.70

# Agent
AGENT_ENERGY_INITIAL = 100.0
AGENT_ENERGY_MINIMUM = 10.0
AGENT_ENERGY_DECAY_RATE = 0.99
AGENT_DEPTH_MAXIMUM = 5

# Experiment
EXPERIMENT_TIMEOUT_DEFAULT = 3600
EXPERIMENT_CHECKPOINT_INTERVAL = 300

# DB
DB_CHECKPOINT_INTERVAL = 100
DB_TIMEOUT = 30

# Logging
LOG_ROTATION_SIZE_MB = 10
LOG_RETENTION_DAYS = 30

# Metrics
CPU_SAMPLE_INTERVAL = 0.1
METRIC_HISTORY_SIZE = 1000

__version__ = '2.0.0'
